export const DEFAULT_FV_DAILY = {
  item1: '', item2: '', item34: '', item5: '', item6: '', item7: '',
  horasVoluntariado: '', horasAulaAssistida: '', horasAulaMinistrada: '',
  gdveTasksStatus: {}, gdveAttendance: false,
  praticas: {
    tratak: false, recitarHonra: false, recitar7Fases: false,
    camara: false, templo: false, porta: false,
    patioAberto: false, patioColunas: false, santuario: false
  }
};

// =========================================================================
// BANCO DE DADOS OFICIAL DOS BASTIÕES (COM ROTAS AUTOMATIZADAS POR ANO)
// =========================================================================

// Função com os IDs exatos fornecidos pelo Henrique
const gerarLinkDoKoha = (anoStr) => {
  const ano = parseInt(anoStr, 10);
  if (!ano) return "#";

  // Mapeamento exato de biblionumber por ano
  const biblioMap = {
    1976: 23101, 1977: 23102, 1978: 23103, 1979: 23104,
    1980: 23105, 1981: 23106, 1982: 23107, 1983: 23108,
    1984: 23109, 1985: 23110, 1986: 23111, 1987: 23112,
    1988: 23113, 1989: 23115, 1990: 23116, 1991: 23117,
    1992: 67560, 1993: 67561, 1994: 73565, 1995: 73566,
    1996: 73567, 1997: 73568, 1998: 73569, 1999: 73570,
    2000: 73571, 2001: 73572, 2002: 73573, 2003: 73574,
    2004: 73575, 2005: 73576, 2006: 73577, 2007: 73578,
    2008: 73579, 2009: 73580, 2010: 73581, 2011: 73582,
    2012: 73583, 2013: 73584, 2014: 73585, 2015: 73586,
    2016: 73587, 2017: 73588, 2018: 73589, 2019: 73590,
    2020: 73591, 2021: 73592, 2022: 73593, 2023: 73594
  };

  const biblionumber = biblioMap[ano];

  // Se o ano estiver no nosso mapa, manda o link direto. 
  // Caso contrário, usa a busca como plano de segurança (fallback).
  if (biblionumber) {
    return `https://biblioteca.acropolebrasil.com.br/cgi-bin/koha/opac-detail.pl?biblionumber=${biblionumber}&query_desc=kw%2Cwrdl%3A%20basti%C3%B5es`;
  } else {
    return `https://biblioteca.acropolebrasil.com.br/cgi-bin/koha/opac-search.pl?idx=&q=Bastiões+${ano}`;
  }
};

// Como são centenas de linhas, usamos uma string em bloco e um mapeamento inteligente para não poluir o código com 500 {objetos}.
const rawBastiões = `
1	OS MUSEUS ACROPOLITANOS	1976	Julho	Não tem	JAL
2	CICLOS E IRREVERSIBILIDADE	1976	Agosto	Não tem	JAL
2	PARA UMA NOVA DISCIPLINA	1976	Agosto	Não tem	JAL
3	ESCOLA DE MOVIMENTO	1976	Setembro	Não tem	JAL
3	NOVA ACRÓPOLE NO MUNDO	1976	Setembro	Não tem	JAL
3	A FILOSOFIA DO RISCO	1976	Setembro	Não tem	JAL
4	OS PERIGOS DO RACISMO	1976	Outubro	Não tem	JAL
5	A PORNOGRAFIA: UM CÂNCER DA SOCIEDADE	1976	Novembro	Não tem	JAL
5	ESCLARECIMENTO SOBRE MEU ANTERIOR: ESCOLA E MOVIMENTO	1976	Novembro	Não tem	JAL
6	FRACASSOS E ÊXITOS (1º)	1976	Dezembro	Não tem	JAL
6	FILOSOFIA E FILOSFISMO	1976	Dezembro	Não tem	JAL
7	FRACASSOS E ÊXITOS ACROPOLITANOS (2º)	1977	Janeiro	Não tem	JAL
7	MENSAGEM DE ANO NOVO (PARIS)	1977	Janeiro	Não tem	JAL
8	NOVA ACRÓPOLE E A ECONOMIA	1977	Fevereiro	Não tem	JAL
8	ECLETISMO	1977	Fevereiro	Não tem	JAL
10	CARTAS À HPB	1977	Maio	Não tem	JAL
10	ODRES NOVOS PARA VINHOS VELHOS	1977	Maio	Não tem	JAL
11	EM DEFESA DA ACRÓPOLE	1977	Junho	Não tem	JAL
11	NECESSIDADE DE MANTER NOSSA UNIDADE DE PROGRAMA	1977	Junho	Não tem	JAL
12	REENCARNAÇÃO DAS ALMAS	1977	Julho	Não tem	JAL
12	NAVEGANDO NA TORMENTA	1977	Julho	Não tem	JAL
12	NO VIGÉSIMO ANIVERSÁRIO (DIA DE NOVA ACRÓPOLE)	1977	Julho	Não tem	JAL
13	A REENCARNAÇÃO	1977	Agosto	Não tem	JAL
14	SOBRE A CONTINUIDADE ATRAVÉS DAS OBRAS	1977	Setembro	Não tem	JAL
14	ORAÇÃO DE UM DISCÍPULO AO SEU MESTRE	1977	Setembro	Não tem	JAL
15	VENDER LARANJAS AO PARAGUAI	1977	Outubro	Não tem	JAL
15	AS MULTINACIONAIS DO VÍCIO	1977	Outubro	Não tem	JAL
16	TEU CORPO FÍSICO	1977	Novembro	Não tem	JAL
16	O MERGULHADOR	1977	Novembro	Não tem	JAL
17	PEQUENO CONTO ORIENTAL	1978	Janeiro	Não tem	JAL
17	TEU CORPO PRANICO	1977	Dezembro	Não tem	JAL
17	CONVIVENCIA	1977	Dezembro	Não tem	JAL
18	QUANDO A ESPERANÇA É DEIXADA PARA TRÁS	1978	Janeiro	Não tem	JAL
19	SEU CORPO ASTRAL	1978	Fevereiro	Não tem	JAL
19	MENSAGEM DO MM EM 1º JANEIRO DE 1978	1978	Fevereiro	Não tem	JAL
20	O QUE É UM REUNIÃO INTERNACIONAL DA OINA	1978	Março	Não tem	JAL
20	MENSAGEM DE PRIMAVERA 1978	1978	Março	Não tem	JAL
21	HPB E A FESTIVIDADE DO LÓTUS BRANCO	1978	Abril	Não tem	JAL
21	UMA APARENTE CONTRADIÇÃO	1978	Abril	Não tem	JAL
22	POLICROMIAS DO RACISMO	1978	Junho	Não tem	JAL
22	15 DE JUNHO: UM NOVO ANIVERSÁRIO DA OINA	1978	Junho	Não tem	JAL
23	A OPÇÃO	1978	Julho	Não tem	JAL
23	O PERIGO DAS CONTRADIÇÕES	1978	Julho	Não tem	JAL
24	COMO NÃO FORAM FEITAS AS PIRÂMIDES DO EGITO	1978	Agosto	Não tem	JAL
25	O ANO DAS 13 LUAS	1978	Setembro	Não tem	JAL
25	MINHA VIAGEM AO EGITO - CAP 1: MEU ENCONTRO COM A GRANDE PIRÂMIDE	1978	Setembro	Não tem	JAL
26	MINHA VIAGEM AO EGITO - CAP 2: NO INTERIOR DA PIRÂMIDE	1978	Outubro	Não tem	JAL
26	O ÍMÃ	1978	Outubro	Não tem	JAL
27	MEDITAÇÕES SOBRE A HUMILDADE	1978	Novembro	Não tem	JAL
27	MINHA VIAGEM AO EGITO - CAP 3: O SERAPHEON E SAKKRA	1978	Novembro	Não tem	JAL
28	FANATISMO: PERIGO DE MORTE	1978	Dezembro	Não tem	JAL
28	MINHA VIAGEM AO EGITO - CAP 4: ABU SIMBEL E ILHA ELEFANTINA	1978	Dezembro	Não tem	JAL
29	MENSAGEM DE JAL - 1º JANEIRO DE 1979	1979	Janeiro	Não tem	JAL
29	MINHA VIAGEM AO EGITO - CAP 5: O NILO E OS MISTERIOSOS REIS NÚBIOS	1979	Janeiro	Não tem	JAL
30	ALGUNS CONSELHOS PRÁTICOS PARA OS NOVOS ACROPOLITANOS	1979	Fevereiro	Não tem	JAL
30	MINHA VIAGEM AO EGITO - CAP 6: TEBAS	1979	Fevereiro	Não tem	JAL
31	NOVIDADES SOBRE O LIVRO DE DZYAN	1979	Março	Não tem	JAL
31	MINHA DESPEDIDA DO EGITO - CAP 7: FINAL	1979	Março	Não tem	JAL
32	ACRÓPOLE: MONISTA, PEDAGÓGICA E IMPERIAL	1979	Maio	Não tem	JAL
32	SOBRE HPB NO DIA DO LÓTUS BRANCO	1979	Maio	Não tem	JAL
33	A OINA NÃO É ORIENTALISTA NEM OCIDENTALISTA, MAS UNIVERSAL	1979	Junho	Não tem	JAL
33	FRATERNIDADE	1979	Junho	Não tem	JAL
34	O LEGAL	1979	Julho	Não tem	JAL
35	ACRÓPOLE: NEM SEITA RELIGIOSA NEM POLÍTICA	1979	Agosto	Não tem	JAL
35	ANTES A ATUAL CRISE ECONÔMICA	1979	Agosto	Não tem	JAL
36	SOBRE "NOVA ACRÓPOLE" INTERNACIONAL	1979	Setembro	Não tem	JAL
36	POMBAS AZUIS	1979	Setembro	Não tem	JAL
37	SOBRE SE O ACROPOLITANO DEVE VIVER O HOJE OU A ETERNIDADE	1979	Outubro	Não tem	JAL
38	O VERDADEIRO PERIGO DO "CULTO À PERSONALIDADE"	1979	Novembro	Não tem	JAL
39	VARRE FILHO, VARRE!	1979	Dezembro	Não tem	JAL
39	COMO DEVEMO ENCARAR, NÓS OS ACROPOLITANOS, AS PROFECIAS SOBRE O ANO 2000?	1979	Dezembro	Não tem	JAL
40	QUANDO O FANATISMO RELIGIOSO SE VOLTA SANGRENTO	1980	Janeiro	Não tem	JAL
40	MENSAGEM DE JAL - 1º JANEIRO DE 1980	1980	Janeiro	Não tem	JAL
41	COMO LER CORRETAMENTE HPB	1980	Fevereiro	Não tem	JAL
41	REFLEXÕES SOBRE AS INFLUÊNCIAS DOS ASTROS EM UM FUTURO IMEDIATO	1980	Fevereiro	Não tem	JAL
42	NÃO EXISTE NADA SUPERIOR A VERDADE	1980	Março	Não tem	JAL
42	PORQUE AS EMBAIXADAS SÃO ASSALTADAS	1980	Março	Não tem	JAL
43	O SIMBOLISMO PRÁTICO DO LÓTUS BRANCO	1980	Maio	Não tem	JAL
44	O PRÓXIMO 15 DE JULHO	1980	Julho	Não tem	JAL
45	CONVIVÊNCIA	1980	Julho	Não tem	JAL
45	A REBELIÃO DOS INTELECTOS	1980	Julho	Não tem	JAL
46	DIFERENTES MANEIRAS DE ORAR	1980	Agosto	Não tem	JAL
46	PODEM SER CONHECIDOS OS DESIGNOS DE DEUS?	1980	Agosto	Não tem	JAL
47	DESTRUIÇÃO DAS TEORIAS ANTROPOLÓGICAS MATERIALISTAS	1980	Setembro	Não tem	JAL
47	AS DUAS IMITAÇÕES	1980	Setembro	Não tem	JAL
47	A TODOS OS PAÍSES ACROPOLITANOS DO HEMISFÉRIO SUL	1980	Setembro	Não tem	JAL
48	NECESSIDADE DE TERMINAR O QUE SE COMEÇA	1980	Outubro	Não tem	JAL
48	MINHA VIAGEM À GRÉCIA - CAP 1	1980	Outubro	Não tem	JAL
49	CONQUISTA-TE E CONQUISTA	1980	Novembro	Não tem	JAL
49	MINHA VIAGEM À GRÉCIA - CAP 2	1980	Novembro	Não tem	JAL
50	A ENFERMIDADE DOS CIUMES	1980	Dezembro	Não tem	JAL
50	MINHA VIAGEM À GRÉCIA - CAP 3	1980	Dezembro	Não tem	JAL
51	MENSAGEM DO MM EM 1º JANEIRO DE 1981	1981	Janeiro	Não tem	JAL
51	MINHA VIAGEM À GRÉCIA - CAP 4	1981	Janeiro	Não tem	JAL
51	FENÔMENOS DA CRÍTICA PSICOLÓGICA	1981	Janeiro	Não tem	JAL
52	EM NOME DE DEUS	1981	Fevereiro	Não tem	JAL
52	MINHA VIAGEM À GRÉCIA - CAP 5	1981	Fevereiro	Não tem	JAL
52	ESCLARECENDO CONCEITOS	1981	Fevereiro	Não tem	JAL
53	???	1981	Março	Não tem	JAL
53	JUVENTUDE DE ESPÍRITO	1981	Março	Não tem	JAL
53	MINHA VIAGEM À GRÉCIA - CAP 6	1981	Março	Não tem	JAL
54	???	1981	Julho	Não tem	JAL
54	MINHA VIAGEM À GRÉCIA - CAP 7	1981	Julho	Não tem	JAL
55	PARA UMA NOVA MORAL ACROPOLITANA	1981	Agosto	Não tem	JAL
55	CABE O POLÍTICO DENTRO DO IDEAL ACROPOLITANO?	1981	Agosto	Não tem	JAL
56	A BOMBA DE NEUTRONS	1981	Setembro	Não tem	JAL
56	POSSIBILIDADE DE UMA GUERRA MUNDIAL	1981	Setembro	Não tem	JAL
57	A NECESSIDADE DE CLAREZA DE EXPRESSÃO	1981	Outubro	Não tem	JAL
58	CUIDADO COM AS MÁSCARAS	1981	Novembro	Não tem	JAL
58	ACRÓPOLE OU EU?	1981	Novembro	Não tem	JAL
59	SUA ATITUDE ANTE OS TEMPOS DUROS	1981	Dezembro	Não tem	JAL
60	MENSAGEM DE ANO NOVO DO MM JAL - 1982	1982	Janeiro	Reafirmação	JAL
61	A AVENTURA PODE SER LOUCA, MAS O AVENTUREIRO DEVE SER SENSATO	1982	Fevereiro	Reafirmação	JAL
61	SOBRE A FRAGILIDADE PSICOLÓGICA DE ALGUNS ACROPOLITANOS	1982	Fevereiro	Reafirmação	JAL
63	A XIX REUNIÃO INTERNACIOANR DE LIMA, PERU	1982	Maio	Reafirmação	JAL
63	DE COMO APROVEITAR O TEMPO	1982	Maio	Reafirmação	JAL
64	GUERRA! (GUERRA ENTRE ARGENTINA E REINO UNIDO)	1982	Junho	Reafirmação	JAL
65	DEPOIS DE 16 SÉCULOS	1982	Julho	Reafirmação	JAL
67	CULTURA E IDEOLOGIA	1982	Setembro	Reafirmação	JAL
68	A CIRCUNSTÂNCIA	1982	Outubro	Reafirmação	JAL
69	CUIDADO COM AS CRISES DO CORPO ASTRAL	1982	Novembro	Reafirmação	JAL
69	A LENTIDÃO	1982	Novembro	Reafirmação	JAL
70	PERIGO: FRAGILIDADE	1982	Dezembro	Reafirmação	JAL
71	AS FORMAS OCULTAS DA AGRESSIVIDADE	1983	Janeiro	Propaganda	JAL
71	UMA BATER DE ASAS DE BRONZE	1983	Janeiro	Propaganda	JAL
72	MENSAGEM DO MM JAL - 1983	1983	Fevereiro	Propaganda	JAL
73	CONSELHOS PARA QUANDO SE SENTIR EXTENUADO	1983	Março	Propaganda	JAL
73	PORQUE CRESCE NOVA ACRÓPOLE	1983	Março	Propaganda	JAL
74	A QUEDA PAULATINA	1983	Maio	Propaganda	JAL
74	FESTA DO LÓTUS BRANCO	1983	Maio	Propaganda	JAL
75	COMO CONSERVAR A LIBERDADE DE CRITÉRIOS	1983	Junho	Propaganda	JAL
76	MAIS SOBRE A LENTIDÃO	1983	Julho	Propaganda	JAL
76	MENSAGENS DE JAL INSPIRADO NO DIA DO LÓTUS BRANCO	1983	Julho	Propaganda	JAL
77	PARA MOVER-SE DE UM LUGAR A OUTRO DEVE ABANDONAR O PRIMEIRO SE QUISER CHEGAR AO SEGUNDO	1983	Agosto	Propaganda	JAL
77	SOBRE OS OVNIS	1983	Agosto	Propaganda	JAL
79	MENSAGEM DE JAL 15 DE JULHO DE 1983	1983	Outubro	Propaganda	JAL
80	E AGORA, O QUE FAZEMOS?	1983	Novembro	Propaganda	JAL
81	PORQUE NÃO ENSINAMOS ESOTERISMO?	1983	Dezembro	Propaganda	JAL
82	MENSAGEM DE MM JAL EM ATHENAS	1984	Janeiro	Integração	JAL
82	QUE NOS ESPERA EM 1984?	1983	Janeiro	Integração	JAL
83	UM VÍCIO BURGUÊS PERNETRA EM NOVA ACRÓPOLE. CUIDADO!	1984	Fevereiro	Integração	JAL
84	O QUE ACONTECE COM A UNESCO?	1984	Março	Integração	JAL
85	XXI REUNIÃO INTERNACIONAL - CARACAS - VENEZUELA	1984	Maio	Integração	JAL
85	SEJAMOS PONTUAIS!	1984	Maio	Integração	JAL
86	ANTE O XXVII ANIVERSÁRIO	1984	Junho	Integração	JAL
86	21 DE JUNHO	1984	Junho	Integração	JAL
87	RESISTA, NÃO ESTÁ SÓ	1984	Julho	Integração	JAL
87	URGE UMA MUDANÇA DE MENTALIDADE	1984	Julho	Integração	JAL
88	PORQUE NÃO SE UNEM... ?	1984	Agosto	Integração	JAL
88	MENSAGEM DE JAL - XXVI ANIVERSÁRIO	1984	Agosto	Integração	JAL
89	O PROGRESSO E EXPANSÃO DA OINA	1984	Setembro	Integração	JAL
89	CITAÇÃO DE KHALIL GIBRAN	1984	Setembro	Integração	JAL
90	PLANOS E INICIATIVAS	1984	Outubro	Integração	JAL
90	PROJETOS	1984	Outubro	Integração	JAL
91	SI PERNO NO. (SIM, PORÉM NÃO)	1984	Novembro	Integração	JAL
91	O DESGASTE: UM PERIGO A ESPERITA	1984	Novembro	Integração	JAL
92	DEVEMOS SER MAIS OU DEVEMOS SER MELHORES	1984	Dezembro	Integração	JAL
93	OS CÃES LADRAM PARA NÓS	1985	Janeiro	Forças Vivas	JAL
93	EXPERIÊNCIA INFANTIL	1985	Janeiro	Forças Vivas	JAL
94	MENSAGEM DE FIM DE ANO DO MM JAL - 1985	1985	Fevereiro	Forças Vivas	JAL
94	NÃO DEVEMOS SACRALIZAR NOSSAS IMPOTÊNCIAS	1985	Fevereiro	Forças Vivas	JAL
95	O "COMPLEXO DE MINOS"	1985	Março	Forças Vivas	JAL
95	VOCÊS SÃO DEMASIADO CRÉDULOS	1985	Março	Forças Vivas	JAL
96	ESTAMOS EM UMA MÁ ÉPOCA DO ANO?	1985	Maio	Forças Vivas	JAL
97	O QUE ACONTECERÁ QUANDO JAL MORRER?	1985	Junho	Forças Vivas	JAL
98	ERA UMA VEZ UM RIO	1985	Julho	Forças Vivas	JAL
98	A PEQUENA MILITANCIA	1985	Julho	Forças Vivas	JAL
99	IMPORTÂNCIA DE UMA BOA ADMINISTRAÇÃO	1985	Agosto	Forças Vivas	JAL
99	NOSSOS INIMIGOS	1985	Agosto	Forças Vivas	JAL
100	REFLEXÕES SOBRE RAÇAS E RACISMOS	1985	Setembro	Forças Vivas	JAL
101	A ARTE DE SER SEMPRE FILÓSOFO	1985	Outubro	Forças Vivas	JAL
101	VOCÊ PODE SER MAIS FORTE DO QUE PENSA	1985	Outubro	Forças Vivas	JAL
102	O QUE PODEMOS RESPONDER QUANDO NOS ACUSAM DE MANIPULAÇÃO?	1985	Novembro	Forças Vivas	JAL
103	ESOTERISMO - FICÇÃO	1985	Dezembro	Forças Vivas	JAL
103	RELANÇAMENTO ESCOLÁSTICO	1985	Dezembro	Forças Vivas	JAL
104	MENSAGEM DO MM JAL EM VIENA	1986	Janeiro	Promoção dos Jovens	JAL
104	O QUE É A MILITÂNCIA	1986	Janeiro	Promoção dos Jovens	JAL
105	PODEMOS ENTRAR EM RELAÇÃO COM OS DEUSES?	1986	Fevereiro	Promoção dos Jovens	JAL
105	ASPECTOR PSICOLÓGICOS DE AUTO-CONTROLE COLETIVO	1986	Fevereiro	Promoção dos Jovens	JAL
106	DO MÉXICO, COM DOR	1986	Março	Promoção dos Jovens	JAL
107	O LÓTUS BRANCO	1986	Maio	Promoção dos Jovens	JAL
107	A CATÁSTROFE DE CHERNOBYL	1986	Maio	Promoção dos Jovens	JAL
107	OS RELÓGIOS BIOLÓGICOS	1986	Maio	Promoção dos Jovens	JAL
108	COMO SE FAZ PROPAGANDA?	1986	Junho	Promoção dos Jovens	JAL
108	ESTAMOS NO MESMO BARCO!	1986	Junho	Promoção dos Jovens	JAL
108	NECESSIDADE DE APROXIMAÇÕES E AFASTAMENTOS COM O MUNDO CIRCUNDANTE	1986	Junho	Promoção dos Jovens	JAL
110	AS PRIMEIRA PROVAS	1986	Agosto	Promoção dos Jovens	JAL
111	O QUE DEVEMOS INFORMAR SOBRA OUTRAS ORGANIZAÇÕES?	1986	Setembro	Promoção dos Jovens	JAL
111	PARA QUE QUERMOS MAIS MEMBROS?	1986	Setembro	Promoção dos Jovens	JAL
112	UMA COISA É CRÍTICA, E OUTRA É ENSINO	1986	Outubro	Promoção dos Jovens	JAL
112	NECESSITAMOS SER MAIS ALEGRES	1986	Outubro	Promoção dos Jovens	JAL
112	O SETE PECADOS CAPITAIS DO CHEFE	1986	Outubro	Promoção dos Jovens	JAL
113	O QUE SE FAZ COM A COTA DINA?	1986	Novembro	Promoção dos Jovens	JAL
113	ALGUNS DE VOCÊS SÃO EXCESSIVAMENTE INGÊNUOS	1986	Novembro	Promoção dos Jovens	JAL
114	O QUE É O JUBILEU?	1986	Dezembro	Promoção dos Jovens	JAL
114	SÍNDROME DE NARCISO	1986	Dezembro	Promoção dos Jovens	JAL
115	O QUE FAZEM OS MORTOS ACROPOLITANOS?	1987	Janeiro	Jubileu	JAL
115	MENSAGEM DE ANO NOVO DO MM JAL EM MADRID	1987	Janeiro	Jubileu	JAL
116	???	1987	Fevereiro	Jubileu	JAL
116	UMA MAGNÍFICA INICIATIVA	1987	Fevereiro	Jubileu	JAL
117	PODE NOS AFETAR A SÍNDROME DE ESTOCOLMO?	1987	Março	Jubileu	JAL
117	FAZ MUITOS SÉCULOS	1987	Março	Jubileu	JAL
118	NECESSIDADE DE CULTIVAR A CONDIÇÃO HERÓICA	1987	Abril	Jubileu	JAL
118	O QUE É A MÍSTICA?	1987	Abril	Jubileu	JAL
119	QUANDO O ESPIRITUAL CAI NO RIDICULO	1987	Maio	Jubileu	JAL
120	GURUS, PREGADORES E ADIVINHOS	1987	Junho	Jubileu	JAL
120	PORQUE NÓS ACROPOLITANOS, NÃO NOS RECORDAMOS DE VIDAS ANTERIORES?	1987	Junho	Jubileu	JAL
121	O QUE NOS CONTOU RENARD	1987	Agosto	Jubileu	JAL
122	O ENIGMA DE HEES	1987	Setembro	Jubileu	JAL
123	UM DETALHE	1987	Outubro	Jubileu	JAL
124	A RUA NOS PERTENCE	1987	Novembro	Jubileu	JAL
125	A DELINQUÊNCIA NOS MEIOS INFORMÁTICOS	1987	Dezembro	Jubileu	JAL
125	DO MARAVILHOSO QUE É TRANSMITIR O IDEAL ACROPOLITANO	1987	Dezembro	Jubileu	JAL
126	1987, ANO DO JUBILEU	1988	Janeiro	Renovação	JAL
126	PORQUE ANO DA RENOVAÇÃO?	1988	Janeiro	Renovação	JAL
127	MENSAGEM DE ANO NOVO JAL	1988	Fevereiro	Renovação	JAL
128	A IMPORTÂNCIA DE RECONHECER E OBTER SEU LUGAR EM NOVA ACRÓPOLE	1988	Março	Renovação	JAL
129	PARA QUE TE CRESÇA A ALMA	1988	Maio	Renovação	JAL
130	O PERIGO DE SER PERFECCIONISTA	1988	Junho	Renovação	JAL
131	PARA UMA CORTESIA ACROPOLITANA	1988	Julho	Renovação	JAL
133	ERRO HUMANO	1988	Setembro	Renovação	JAL
133	NOVA LUZ SOBRE A "PAIDEIA" GREGA NA BIBLIOTECA DE RODAS	1988	Setembro	Renovação	JAL
134	MINHA VIAGEM À ÍNDIA	1988	Outubro	Renovação	JAL
135	NECESSIDADE DE TOLERÂNCIA ATIVA	1988	Novembro	Renovação	JAL
135	DEVEMOS GERAR NOVOS LEITORES	1988	Novembro	Renovação	JAL
136	O SISTEMA PIRAMIDAL COMO ELEMENTO DE CONCÓRDIA	1988	Dezembro	Renovação	JAL
136	JÁ SE MANIFESTA A NOVA IDADE MÉDIA	1988	Dezembro	Renovação	JAL
137	MENSAGEM DE ANO NOVO DE MM	1989	Janeiro	Afirmação	JAL
138	AS IDADES ESOTÉRICAS NO HOMEM	1989	Fevereiro	Afirmação	JAL
138	HONREMOS AS VERDADES COM A PRATICA - HPB	1989	Fevereiro	Afirmação	JAL
139	CRISE ECONÔMICA NO VATICANO	1989	Abril	Afirmação	JAL
140	EXISTEM RELAMENTE OS MESTRES DE SABEDORIA?	1989	Abril	Afirmação	JAL
140	LIBERDADE DE OBEDIÊNCIA	1989	Abril	Afirmação	JAL
141	A BOMBA MAIS TERRÍVEL DO MUNDO	1989	Junho	Afirmação	JAL
141	NOS CAÍMOS EM CONTRADIÇÃO?	1989	Junho	Afirmação	JAL
142	IMPÉRIO! FELIZ ANIVERSÁRIO	1989	Julho	Afirmação	JAL
142	SABIA QUE...?	1989	Julho	Afirmação	JAL
143	AGORA SE DIZ QUE DEMOS FORMAÇÃO A HITLER!	1989	Agosto	Afirmação	JAL
144	A PRATICIDADE DA FILOSOFIA ACROPOLITANA	1989	Setembro	Afirmação	JAL
144	CUIDADO COM O FANATISMO!	1989	Setembro	Afirmação	JAL
145	IMPORTÂNCIA DA AUTOFORMAÇÃO ACROPOLITANA	1989	Outubro	Afirmação	JAL
145	O BOM ACROPOLITANO	1989	Outubro	Afirmação	JAL
146	QUE ATITUDE DEVEMOS ASSUMIR ANTE A ALEGADA APARIÇÃO DE DISCO VOADORES?	1989	Novembro	Afirmação	JAL
147	O UNIFORME DOS NOVO FILÓSOFOS	1989	Dezembro	Afirmação	JAL
147	COMO ENCARAR MEU PROGRESSO ESPIRITUAL E PSICOLÓGICO EM 1990?	1989	Dezembro	Afirmação	JAL
148	COMO SE DESPERTAM OS PODERES OCULTOS NO HOMEM?	1990	Janeiro	Militância	JAL
148	MENSAGEM DE ANO NOVO DO MM JAL	1990	Janeiro	Militância	JAL
149	PORQUE ANO DA MILITÂNCIA?	1990	Fevereiro	Militância	JAL
149	A MILITÂNCIA COMO REGENERADORA	1990	Fevereiro	Militância	JAL
149	A IGREJA A ORAÇÃO E O YOGA	1990	Fevereiro	Militância	JAL
150	NADA EM EXCESSO	1990	Março	Militância	JAL
150	A INFLUÊNICA DE AQUÁRIO E A EXPLOSÃO DE LIBERDADE NO LESTE EUROPEU	1990	Março	Militância	JAL
151	HPB - EXEMPLO DE MILITÂNCIA	1990	Março	Militância	JAL
151	DIMINUE A VOCAÇÃO RELIGIOSA?	1990	Março	Militância	JAL
152	IMPORTÂNCIA DE NOSSA PRESENÇA MILITANTE NAS RUAS	1990	Junho	Militância	JAL
153	O QUE FAZER ANTE A NOVA ORDEM DO MUNDO?	1990	Junho	Militância	JAL
154	HÁ ALGUNS DIAS ATRÁS TIVE UM SONHO	1990	Agosto	Militância	JAL
154	OS TERRÍVEIS PERIGOS DO USO DAS DROGAS	1990	Agosto	Militância	JAL
155	SER ACROPOLITANO	1990	Setembro	Militância	JAL
155	CONSTATAÇÃO DA NECESSIDADE DE UMA ORDEM NATURAL	1990	Setembro	Militância	JAL
156	EVOLUIU A OINA TANTO QUANTO O MUNDO NOS ÚLTIMOS 30 ANOS?	1990	Outubro	Militância	JAL
156	COMO FAZER COM QUE IMPULSO ESPIRITUAL PASSE ATRAVÉS DE NÓS E SE MANIFESTE	1990	Outubro	Militância	JAL
157	O ESPELHO INTERIOR	1990	Novembro	Militância	JAL
157	BÁRBAROS NO LIMINIAR DAS PORTAS	1990	Novembro	Militância	JAL
158	DEUS NÃO QUER O CONTROLE DE NATALIDADE?	1990	Dezembro	Militância	JAL
158	MACHAR ENTRE OS MORTOS	1990	Dezembro	Militância	JAL
159	MENSAGEM DO MM JAL 1991	1991	Janeiro	Constatação	JAL
160	ASPECTOS DO FENÔMENO DA GUERRA	1991	Fevereiro	Constatação	JAL
160	NO ANO DA CONSTATAÇÃO	1991	Fevereiro	Constatação	JAL
161	A REBELIÃO DAS RAÇAS	1991	Abril	Constatação	JAL
161	EM QUE CONSISTE NOSSA FRATERNIDADE ACROPOLITANA?	1991	Abril	Constatação	JAL
162	NO PRIMEIRO CENTENÁRIO DA MORTE DE HPB	1991	Maio	Constatação	JAL
162	1891 - 8 DE MAIO - 1991	1991	Maio	Constatação	JAL
163	NECESSIDADE DE MAIOR E MELHOR LEITURA E FORMAÇÃO	1991	Junho	Constatação	JAL
163	PARA UMA NOVA CONVIVÊNCIA	1991	Junho	Constatação	JAL
164	NÃO TENHO TEMPO NEM DINHEIRO	1991	Julho	Constatação	JAL
164	NOVA ACRÓPOLE NO MUNDO ATUAL	1991	Julho	Constatação	JAL
165	NÃO ESCONDAMOS A NOSSA IDENTIDADE	1991	Agosto	Constatação	JAL
165	COMO SERÁ NOVA ACRÓPOLE NO TERCEIRO MILÊNIO?	1991	Agosto	Constatação	JAL
166	NOVA LINGUAGEM	1991	Setembro	Constatação	JAL
166	AS NOVAS MURALHAS	1991	Setembro	Constatação	JAL
167	SOCIOPOLITICA	1991	Outubro	Constatação	JAL
167	DEVEMOS RELACIONAR CONHECIMENTOS TRADICIONAIS COM A CIÊNCIA ATUAL?	1991	Outubro	Constatação	JAL
167	NECESSÁRIO CONTROLE SOBRE O USO DE NOSSO TEMPO	1991	Outubro	Constatação	JAL
168	O BASTIÃO	1991	Novembro	Constatação	DSG
168	O FUTURO ACROPOLITANO	1991	Novembro	Constatação	DSG
169	MOZART É UM GÊNIO	1991	Dezembro	Constatação	DSG
169	VAI-SE 1991...	1991	Dezembro	Constatação	DSG
170	MENSAGEM DE ANO NOVO - 1992 - UMA	1992	Janeiro	Pacto	DSG
170	A FELICIDADE	1992	Janeiro	Pacto	DSG
171	1992, ANO DO PACTO	1992	Fevereiro	Pacto	DSG
172	IDEOLOGIAS E IDEALISTAS	1992	Março	Pacto	DSG
172	TRIUNFAR NA VIDA	1992	Março	Pacto	DSG
172	FRASES DE JAL	1992	Março	Pacto	DSG
173	O LONGO CAMINHO DA HUMANIDADE	1992	Maio	Pacto	DSG
173	8 DE MAIO DE 1992	1992	Maio	Pacto	DSG
174	 FESTAS LUSTRAIS	1992	Junho	Pacto	DSG
174	A REPETIÇÃO	1992	Junho	Pacto	DSG
175	NOVA ACRÓPOLE: 35 ANOS DE VIDA	1992	Julho	Pacto	DSG
175	NÓS TODOS QUEREMOS MAIS	1992	Julho	Pacto	DSG
176	ALGUNS PROBLEMAS A CONFRONTAR NO CAMINHO DO IDEALISMO	1992	Agosto	Pacto	DSG
177	COISAS QUE NOS CANSAM E NOS DESCANSAM	1992	Setembro	Pacto	DSG
177	SOMOS PESSIMISTAS OU OTIMISTAS?	1992	Setembro	Pacto	DSG
178	AS TRÊS VIRTUDES DO BOM DISCÍPULO	1992	Outubro	Pacto	DSG
179	O MEDO DA MUDANÇA	1992	Novembro	Pacto	DSG
179	UM PERDÃO TARDIO	1992	Novembro	Pacto	DSG
180	TERMINA O ANO DO PACTO	1992	Dezembro	Pacto	DSG
180	SABER ESCUTAR	1992	Dezembro	Pacto	DSG
181	TEBAS, UM ESTADO DE CONSCIÊNCIA	1993	Janeiro	Ordem	DSG
181	MENSAGME DE ANO NOVO - 1993 - TEBAS EGITO	1993	Janeiro	Ordem	DSG
182	1993, ANO DA ORDEM	1993	Fevereiro	Ordem	DSG
182	A ORDEM	1993	Fevereiro	Ordem	DSG
183	OS HOMENS TEM MEDO DOS HOMENS	1993	Março	Ordem	DSG
183	O PODER DAS COMPARAÇÕES	1993	Março	Ordem	DSG
184	TRABALHE PARA ELES HOJE, E ELES TRABALHARÃO PARA VOCÊ AMANHÃ	1993	Maio	Ordem	DSG
184	PLENILÚNIO DE MAIO	1993	Maio	Ordem	DSG
185	PARA QUE E PARA ONDE	1993	Junho	Ordem	DSG
185	MÊS DE JUNHO... DIA DOS VIVOS ACROPOLITANOS	1993	Junho	Ordem	DSG
186	INTOLERÂNCIA ATIVA, TOLERÂNCIA PASSIVA	1993	Julho	Ordem	DSG
186	TRINTA E SEIS ANOS ACROPOLITANOS	1993	Julho	Ordem	DSG
187	PRINCÍPIO, MEIOS E FINALIDADES	1993	Agosto	Ordem	DSG
187	NOSSAS CONVICÇÕES	1993	Agosto	Ordem	DSG
188	INCENDEIA A TERRA	1993	Setembro	Ordem	DSG
188	OS ESTADOS DE CONSCIÊNCIA SÃO CONTAGIOSOS	1993	Setembro	Ordem	DSG
189	O COFRE DE OUTRO	1993	Outubro	Ordem	DSG
190	A MILITÂNICA RELAXADA	1993	Novembro	Ordem	DSG
190	ESCUDO QUE PROTEGEM QUE DESTROEM	1993	Novembro	Ordem	DSG
191	OS ENSINAMENTOS E SUA APLICAÇÃO	1993	Dezembro	Ordem	DSG
191	OS DEFEITOS ANULAM AS VIRTUDES?	1993	Dezembro	Ordem	DSG
192	MENSAGEM DE ANO NOVO - 1994 - COLÔMBIA	1994	Janeiro	Unificação	DSG
192	O MULTOFACETADO DEUS APOLO	1994	Janeiro	Unificação	DSG
193	A UNIFICAÇÃO	1994	Fevereiro	Unificação	DSG
193	COMO REALIZAREMOS A UNIFICAÇÃO?	1994	Fevereiro	Unificação	DSG
194	O FÁCIL E O DIFÍCIL	1994	Março	Unificação	DSG
194	ZOROASTRO	1994	Março	Unificação	DSG
195	MES DE MAIO, NOSSO MESTRE JAL	1994	Maio	Unificação	DSG
195	MAIO: A MESTRA HPB	1994	Maio	Unificação	DSG
196	AS CRÍTICA O MAL DO NOSSO TEMPO	1994	Junho	Unificação	DSG
196	CONVICÇÃO E FANATISMO	1994	Junho	Unificação	DSG
197	COMPROMISSO E LIBERDADE	1994	Julho	Unificação	DSG
197	NUESTRO ANIVERSÁRIO (NOSSO ANIVERSÁRIO)	1994	Julho	Unificação	DSG
198	A AMIZADE FIOLOSÓFICA	1994	Agosto	Unificação	DSG
198	NOSSA PERSONALIDADE	1994	Agosto	Unificação	DSG
199	A RESPONSABILIDADE	1994	Setembro	Unificação	DSG
199	O ESTRANHO PRAZER DO ÚLTIMO MINUTO	1994	Setembro	Unificação	DSG
200	ALFA E ÔMEGA	1994	Outubro	Unificação	DSG
200	ÔMEGA	1994	Outubro	Unificação	DSG
201	NOSSA BANDEIRA ACROPOLITANA	1995	Setembro	Concórdia	DSG
201	O QUE APRENDO E O QUE SEI	1994	Novembro	Unificação	DSG
201	O ESPELHO DUPLO	1994	Novembro	Unificação	DSG
202	DESPEDIMOS DO ANO DA UNIFICAÇÃO	1994	Dezembro	Unificação	DSG
202	QUEREMOS PROVAS	1994	Dezembro	Unificação	DSG
203	MENSAGEM DE ANO NOVO - 1995	1995	Janeiro	Concórdia	DSG
203	ANO DA CONCÓRDIA	1995	Janeiro	Concórdia	DSG
204	MAIS SOBRE A CONCÓRDIA	1995	Fevereiro	Concórdia	DSG
204	QUALIDADE DE VIDA	1995	Fevereiro	Concórdia	DSG
205	ISTO NÃO É O QUE EU ESPERAVA...	1995	Março	Concórdia	DSG
205	O QUE QUEREMOS E O QUE TEMOS	1995	Março	Concórdia	DSG
206	HONRE AS VERDADES COM A PRÁRICA - HPB	1995	Maio	Concórdia	DSG
206	IRMANDADE	1995	Maio	Concórdia	DSG
207	A HONRA ESTÁ NO MUNDO, MAS ESTÁ OCULTA	1995	Junho	Concórdia	DSG
207	LIMTES E LIMITAÇÕES	1995	Junho	Concórdia	DSG
208	O CRESCIMENTO POSITIVO	1995	Julho	Concórdia	DSG
208	O QUE E COMPARAR?	1995	Julho	Concórdia	DSG
209	NOSSO IDEAL E SUA EXPRESSÃO NO MUNDO	1995	Agosto	Concórdia	DSG
209	O MUNDO EM QUE VIVEMOS	1995	Agosto	Concórdia	DSG
210	ANDANDO NO CAMINHO, COM OU SEM MEDO	1995	Setembro	Concórdia	DSG
211	PARA O MEU MESTRE: 4 ANOS DEPOIS	1995	Outubro	Concórdia	DSG
212	NOSSO SÍMBOLO ESCOLÁSTICO	1995	Novembro	Concórdia	DSG
212	A AÇÃO	1995	Novembro	Concórdia	DSG
213	CONCÓRDIA, NÃO PODEMOS NOS DESPEDIR DE VOCÊ	1995	Dezembro	Concórdia	DSG
213	HINO DE NOVA ACRÓPOLE	1995	Dezembro	Concórdia	DSG
214	MENSAGEM DE ANO NOVO	1996	Janeiro	Valor	DSG
214	SOBRE O VALOR	1996	Janeiro	Valor	DSG
215	NOSSAS ATIVIDADES	1996	Fevereiro	Valor	DSG
215	ATUAR COM O CORAÇÃO	1996	Fevereiro	Valor	DSG
216	IRMÃOS ACROPOLITANOS	1996	Março	Valor	DSG
216	A MORTE	1996	Março	Valor	DSG
217	8 DE MAIO	1996	Maio	Valor	DSG
218	O QUE É O PROVACIONISMO?	1996	Junho	Valor	DSG
218	NECESSITAMOS APROVAÇÃO PARA TUDO O QUE FAZEMOS?	1996	Junho	Valor	DSG
219	NOSSO ANIVERSÁRIO	1996	Julho	Valor	DSG
219	A CÓLERA E A CORAGEM	1996	Julho	Valor	DSG
219	NOSSAS CELEBRAÇÕES	1996	Agosto	Valor	DSG
220	A ANTIGUIDADE DA HUMANIDADE	1996	Agosto	Valor	DSG
221	NOVA ACRÓPOLE: ESCOLA DE FILOSOFIA, ESCOLA DE MISTÉRIOS	1996	Setembro	Valor	DSG
221	O MELHOR DOS MUNDOS	1996	Setembro	Valor	DSG
222	RAÍZES FÉRTEIS E RAMOS RESSECADOS	1996	Outubro	Valor	DSG
222	NOSSOS PEQUENOS-GRANDES HERÓIS	1996	Outubro	Valor	DSG
223	A IDEOLOGIA ACROPILITANA	1996	Novembro	Valor	DSG
223	A DEBILIDADE	1996	Novembro	Valor	DSG
224	O BEM ESTAR	1996	Dezembro	Valor	DSG
224	EGOÍSMO/EGOCENTRISMO	1996	Dezembro	Valor	DSG
225	MENSAGEM DE ANO NOVO - 1997	1997	Janeiro	Lei	DSG
225	A LEI	1997	Janeiro	Lei	DSG
226	DARMA E KARMA	1997	Fevereiro	Lei	DSG
226	O ORGANIZATIVO	1997	Fevereiro	Lei	DSG
227	A PRIMAVERA E A JUVENTUDE	1997	Março	Lei	DSG
227	A LEITURA	1997	Março	Lei	DSG
228	NO MÊS DE MAIO - PALAVRA DOS MESTRES	1997	Maio	Lei	DSG
228	SABER QUERER	1997	Maio	Lei	DSG
229	SOBRE A PURIFICAÇÃO - FESTAS LUSTRAIS 1997	1997	Junho	Lei	DSG
230	NOVA ACRÓPOLE: 40 ANOS	1997	Julho	Lei	DSG
230	O QUE NOS ENSINA O KARMA	1997	Julho	Lei	DSG
231	A RENOVAÇÃO	1997	Agosto	Lei	DSG
231	EVOLUÇÃO	1997	Agosto	Lei	DSG
232	LER NA NATUREZA	1997	Setembro	Lei	DSG
232	VENCER O MEDO	1997	Setembro	Lei	DSG
233	DIA DE ODERENDAS, DIA DE RECORDAÇÕES	1997	Outubro	Lei	DSG
233	A CONFSSÃO NEGATIVA	1997	Outubro	Lei	DSG
234	PERGUNTAS E RESPOSTAS	1997	Novembro	Lei	DSG
235	NOSSOS INIMIGOS	1997	Dezembro	Lei	DSG
236	MENSAGEM DE ANO NOVO 1998	1998	Janeiro	Ação	DSG
236	ANO DA AÇÃO	1998	Janeiro	Ação	DSG
237	VONTADE AÇÃO	1998	Fevereiro	Ação	DSG
238	NOSSAS AÇÕES	1998	Março	Ação	DSG
238	DIFICULDADE PARA TRABALHAR EM EQUIPE	1998	Março	Ação	DSG
239	NO MÊS DE MAIO - AS GRANDES FÓRMULAS DE AÇÃO	1998	Maio	Ação	DSG
239	AS BARREIRAS INVISÍVEIS DA AÇÃO	1998	Maio	Ação	DSG
240	SER DISCÍPULO	1998	Junho	Ação	DSG
240	RENASCIMENTO	1998	Junho	Ação	DSG
241	41 ANOS DE UM IDEAL EM AÇÃO	1998	Julho	Ação	DSG
241	O ENTUSIASMO É IMPOSSÍVEL SEM UM IDEAL	1998	Julho	Ação	DSG
242	O IDEAL: O ARQUÉTIPO E O HUMANO	1998	Agosto	Ação	DSG
242	A AÇÃO VENCE O MEDO	1998	Agosto	Ação	DSG
243	O LONGOS DEDOS DO MEDO	1998	Setembro	Ação	DSG
243	A NEGLIGUÊNCIA: UMA FORMA DE INAÇÃO	1998	Setembro	Ação	DSG
243	A TODOS OS PAÍSES DO EMISFÉRIO SUL	1998	Setembro	Ação	DSG
244	7 DE OUTUBRO DE 1998, 7 ANOS DE UM LONGO CICLO	1998	Outubro	Ação	DSG
244	UM PEQUENA-GRANDE OFERENDA: "A PEQUENA MILITÂNCIA"	1998	Outubro	Ação	DSG
245	O SEGREDO DAS PEQUENAS COSIAS	1998	Novembro	Ação	DSG
245	CONCILIAR OS ENSINAMENTOS FILOSÓFICOS COM A VIDA PRÁTICA	1998	Novembro	Ação	DSG
246	O ESFORÇO	1998	Dezembro	Ação	DSG
246	CATÁSTROFES NATURAIS	1998	Dezembro	Ação	DSG
247	MENSAGEM DE ANO NOVO 1999 - MÉXICO	1999	Janeiro	Atenção	DSG
247	UMAS POUCAS PALAVRAS ACERCA DA ATENÇÃO	1999	Janeiro	Atenção	DSG
248	A ATENÇÃO E OS SENTIDOS	1999	Fevereiro	Atenção	DSG
248	A DILIGÊNCIA	1999	Fevereiro	Atenção	DSG
249	PERSEVERANÇA- CONSTÂNCIA MARÇO	1999	Março	Atenção	DSG
249	A DISTRAÇÃO	1999	Março	Atenção	DSG
250	O MÊS DE MAIO, PALAVRA DOS MESTRES	1999	Maio	Atenção	DSG
250	OS MOTIVOS OCULTOS DA VIOLÊNCIA, A PIOR PRAGA DO FINAL DO SÉCULO	1999	Maio	Atenção	DSG
251	MAIS SOBRE A ATENÇÃO, PREVENÇÃO - ANTECIPAÇÃO	1999	Junho	Atenção	DSG
251	VOLUNTARIADO	1999	Junho	Atenção	DSG
252	NOSSOS 42 ANOS DE VIDA	1999	Julho	Atenção	DSG
252	A ATENÇÃO E O PODER DA CONSCIÊNCIA	1999	Julho	Atenção	DSG
253	NOVA ACRÓPOLE "SOB MEDIDA"	1999	Agosto	Atenção	DSG
253	VANTAGENS E DESVANTAGENS DA IDADE	1999	Agosto	Atenção	DSG
254	ATÉ ONDE VÃO A RAZÃO E OS SENTIMENTOS HUMANOS?	1999	Setembro	Atenção	DSG
254	A MANIPULAÇÃO NOS ALCANÇA	1999	Setembro	Atenção	DSG
255	OUTRA VEZ, OBRIGADA JAL	1999	Outubro	Atenção	DSG
255	1991 - 1999 OBRIGADA SENHOR!	1999	Outubro	Atenção	DSG
256	A ALEGRIA NÃO ESTÁ NAS COISAS, MAS DENTRO DE NÓS	1999	Novembro	Atenção	DSG
256	GRANDES MUDANÇAS ANTES UM NOVO MILÊNIO	1999	Novembro	Atenção	DSG
257	O ANO 2000	1999	Dezembro	Atenção	DSG
257	PERSONALISMO E PERSONALIDADE	1999	Dezembro	Atenção	DSG
258	MENSAGE DE ANO NOVO - 2000 - ESPANHA	2000	Janeiro	Inícios	DSG
258	ANO DOS INÍCIOS	2000	Janeiro	Inícios	DSG
259	JANO, O MAIS ANTIGO DOS DEUSES	2000	Fevereiro	Inícios	DSG
259	O PRIMEIRO PASSO	2000	Fevereiro	Inícios	DSG
260	SABER FALAR	2000	Março	Inícios	DSG
260	MURALHAS E PORTAS	2000	Março	Inícios	DSG
261	MESTRE E DISCÍPULOS	2000	Maio	Inícios	DSG
261	NO MÊS DE MAIO: A MEMÓRIA VIVA DOS MESTRES	2000	Maio	Inícios	DSG
262	TERMINAR TUDO O QUE SE COMEÇA	2000	Junho	Inícios	DSG
262	A DOR	2000	Junho	Inícios	DSG
263	CONCENTRAÇÃO	2000	Julho	Inícios	DSG
263	O QUE É A PRECISÃO?	2000	Julho	Inícios	DSG
264	MANIPULAÇÃO MENTAL	2000	Agosto	Inícios	DSG
264	SEGURANÇA EM SI MESMO	2000	Agosto	Inícios	DSG
265	O VALOR DA PALAVRA	2000	Setembro	Inícios	DSG
265	ENGANAR AO ENGANADOR	2000	Setembro	Inícios	DSG
266	AO NOSSO MESTRE JAL	2000	Outubro	Inícios	DSG
266	ALGO PARA RECORDAR	2000	Outubro	Inícios	DSG
267	VENCER OU DAR-SE POR VENCIDO	2000	Novembro	Inícios	DSG
267	O KARMA ALHEIO	2000	Novembro	Inícios	DSG
268	OUTRA VEZ, O ANO DOS INÍCIOS	2000	Dezembro	Inícios	DSG
268	AS COMPARAÇÕES	2000	Dezembro	Inícios	DSG
269	MENSAGEM DE ANO NOVO - 2001 - FRANÇA	2001	Janeiro	Centro	DSG
269	ANO DE CENTRO	2001	Janeiro	Centro	DSG
270	ONDE ESTÁ O CENTRO DE CADA UM?	2001	Fevereiro	Centro	DSG
270	A CONSCIÊNCIA DO CENTRO	2001	Fevereiro	Centro	DSG
271	GOSTAS DE SABEDORIA	2001	Março	Centro	DSG
271	AS DIFERENTES VELOCIDADES DA IDADE MÉDIA	2001	Março	Centro	DSG
272	MENSAGEM DO MM DSG - RIMM ATENAS - 2001	2001	Maio	Centro	DSG
272	MÊS DE MAIO: PALAVRAS DOS MESTRES	2001	Maio	Centro	DSG
273	ALGO MAIS SOBRE O CENTRO	2001	Junho	Centro	DSG
273	DISTINTAS FORMAS DE ORGULHO	2001	Junho	Centro	DSG
274	OS NOVOS MENESTRÉIS	2001	Julho	Centro	DSG
274	A PERSONALIDADE E O CENTRO	2001	Julho	Centro	DSG
275	CHEGAR AO CENTRO OU SUBJETIVIDADE?	2001	Agosto	Centro	DSG
275	UMA LIÇÃO DE HISTÓRIA	2001	Agosto	Centro	DSG
276	A VOCAÇÃO	2001	Setembro	Centro	DSG
276	SOBRE A JUVENTUDE	2001	Setembro	Centro	DSG
277	DEZ ANOS, UM CICLO	2001	Outubro	Centro	DSG
277	HPB TAMBÉM EM OUTUBRO	2001	Outubro	Centro	DSG
278	A INFORMAÇÃO E O MEDO	2001	Novembro	Centro	DSG
278	O INVERSO DA ARTE	2001	Novembro	Centro	DSG
279	A OBEDIÊNCIA	2001	Dezembro	Centro	DSG
279	O TRABALHO	2001	Dezembro	Centro	DSG
280	MENSAGEM DE ANO NOVO - TEL AVIV	2002	Janeiro	Heroísmo	DSG
280	O HEROÍSMO	2002	Janeiro	Heroísmo	DSG
281	OS SEMIDEUSES	2002	Fevereiro	Heroísmo	DSG
281	OS INTÉRPRETES	2002	Fevereiro	Heroísmo	DSG
282	O HERÓI E SEUS COMPANHEIROS	2002	Abril	Heroísmo	DSG
282	A MALDADE	2002	Abril	Heroísmo	DSG
283	ONDE NÃO HÁ LUTA, NÃO HÁ MÉRITO	2002	Maio	Heroísmo	DSG
283	NO MÊS DE MAIO, A NOSSOS HERÓICOS MESTRES	2002	Maio	Heroísmo	DSG
284	FESTAS LUSTRAIS	2002	Junho	Heroísmo	DSG
284	O HERÓI JUSTICEIRO	2002	Junho	Heroísmo	DSG
285	NUESTRO ANIVERSÁRIO (NOSSO ANIVERSÁRIO)	2002	Julho	Heroísmo	DSG
285	O HERÓI E A VIAGEM	2002	Julho	Heroísmo	DSG
286	O HERÓI E OS MONSTROS	2002	Agosto	Heroísmo	DSG
286	ROTINA E FILOSOFIA	2002	Agosto	Heroísmo	DSG
287	EL HÉROE Y SUS CAIDAS	2002	Setembro	Heroísmo	DSG
287	LA TIERRA ESTÁ ENFERMA	2002	Setembro	Heroísmo	DSG
288	JUBILEO DEDIDADO A MI MAESTRO	2002	Outubro	Heroísmo	DSG
288	LA IDENTIDAD DEL HÉROE	2002	Outubro	Heroísmo	DSG
289	EL HÉROE Y LA JUVENTUD	2002	Novembro	Heroísmo	DSG
289	UNA EXPERIÊNCIA DE VIDA Y MUERTE	2002	Novembro	Heroísmo	DSG
290	EL HÉROE Y EL FINAL DE CAMINO	2002	Dezembro	Heroísmo	DSG
290	LAS PUERTAS	2002	Dezembro	Heroísmo	DSG
291	MENSAGEM DE ANO NOVO 2004	2003	Janeiro	Vitória	DSG
291	A VITÓRIA	2003	Janeiro	Vitória	DSG
292	A VITÓRIA VALOROSA	2003	Fevereiro	Vitória	DSG
293	A VIRÓRIA IMPETUOSA	2003	Março	Vitória	DSG
294	A LOS MAESTROS	2003	Maio	Vitória	DSG
294	EXTRACTO DEL MENSAJE DE CLAUSURA. RIMM 2003.	2003	Maio	Vitória	DSG
295	A VITÓRIA TRANQUILA	2003	Junho	Vitória	DSG
296	A VIRÓRIA COM SACRIFÍCIO	2003	Julho	Vitória	DSG
296	15 DE JULHO: 1957 - 2003	2003	Julho	Vitória	DSG
297	A VITÓRIA ASTUTA	2003	Agosto	Vitória	DSG
297	A ARTE DE MEDIR-SE A SI MESMO	2003	Agosto	Vitória	DSG
298	LA CAVERNA FUNCIONA	2003	Setembro	Vitória	DSG
299	PEQUEÑO HOMENAJE A UN GRAN MAESTRO	2003	Outubro	Vitória	DSG
299	VENCER EN LA NOCHE	2003	Outubro	Vitória	DSG
300	OBJETIVOS A CONQUISTAR	2003	Novembro	Vitória	DSG
300	ESTAMOS EN EL MISMO BARCO	2003	Novembro	Vitória	DSG
301	ANTE LAS PUERTAS DE UN NUEVO AÑO	2003	Dezembro	Vitória	DSG
301	VOLVER A COMENZAR	2003	Dezembro	Vitória	DSG
302	MENSAGE AÑO NUEVO 2004	2004	Janeiro	Oportunidade	DSG
302	KAIROS. DIOS DE LA OPRTUNIDAD	2004	Janeiro	Oportunidade	DSG
303	KAIROS Y LA JUSTA MEDIDA	2004	Fevereiro	Oportunidade	DSG
303	LO QUE JAL NOS DIJO SOBRE LA OPRTUNIDAD	2004	Fevereiro	Oportunidade	DSG
304	KAIROS Y PROMETEO	2004	Março	Oportunidade	DSG
304	EL TIEMPO: AMIGO O ENEMIGO?	2004	Março	Oportunidade	DSG
305	KAYROS Y KRONOS	2004	Maio	Oportunidade	DSG
305	EL GENIO DE LOS MAESTROS	2004	Maio	Oportunidade	DSG
306	LA OPRTUNIDAD Y LA FORTUNA	2004	Junho	Oportunidade	DSG
306	EL AMOR POR EL ESTUDIO	2004	Junho	Oportunidade	DSG
307	ANTE NUESTRO 47º ANIVERSARIO	2004	Julho	Oportunidade	DSG
307	KAIROS Y EL ARTE DE LA TRANSMISSIÓN	2004	Julho	Oportunidade	DSG
308	KAIROS. TIEMPO PRESENTE	2004	Agosto	Oportunidade	DSG
308	LA HUMANIDAD	2004	Agosto	Oportunidade	DSG
309	KAIROS Y EL KARMA	2004	Setembro	Oportunidade	DSG
309	UN TIEMPO ESPECIAL	2004	Setembro	Oportunidade	DSG
310	KAIROS Y LA RENOVACIÓN	2004	Outubro	Oportunidade	DSG
310	UN PRECURSOSR DEL HOMBRE NUEVO	2004	Outubro	Oportunidade	DSG
311	KAIROS Y LA UNIDAD	2004	Novembro	Oportunidade	DSG
311	LOS INSTINTOS Y LA INTELIGENCIA	2004	Novembro	Oportunidade	DSG
312	KAIROS POLIFACÉTICO Y PLÁSTICO	2004	Dezembro	Oportunidade	DSG
312	ÁNGELES Y DEMONIOS	2004	Dezembro	Oportunidade	DSG
313	MENSAJE DE ANO NUEVO 2005	2005	Janeiro	Experiência	DSG
313	ALGUNAS CITAS SOBRE LA EXPERIÊNCIA	2005	Janeiro	Experiência	DSG
314	LA EXPERIENCIA	2005	Fevereiro	Experiência	DSG
314	NUESTRAS REUNIONES INTERNACIONALES	2005	Fevereiro	Experiência	DSG
315	ADQUIRIR EXPERIENCIA	2005	Março	Experiência	DSG
315	LA RIMM DEL 2005	2005	Março	Experiência	DSG
316	LA CADENA MÁGICA	2005	Maio	Experiência	DSG
316	LA NECESSARIA EXPERIENCIA	2005	Maio	Experiência	DSG
316	LA INOLVIDADE RIMM DE L'AQUILA	2005	Maio	Experiência	BDC
317	LOS SOLSTICIOS, UNA OPORTUNIDAD PARA DECIR: PRESENTE!	2005	Junho	Experiência	BDC
317	LA PROPRIA EXPERIENCIA	2005	Junho	Experiência	DSG
317	EN EL SOLSTICIO DE JUNIO	2005	Junho	Experiência	DSG
318	LAS EXPERIÊNCIAS MAL ASSIMILADAS	2005	Julho	Experiência	DSG
318	48 AÑA TRIUNFAL	2005	Julho	Experiência	BDC
319	LA EXPERIENCIA E LAS REPETICIONES	2005	Agosto	Experiência	DSG
319	LA MILITANCIA ES EFICACIA	2005	Agosto	Experiência	BDC
320	EXPERIÊNCIA PARA CORREGIR ERRORES	2005	Setembro	Experiência	DSG
321	EL ESPIRITU DE LA PROPAGANDA	2005	Setembro	Experiência	BDC
321	JAL: UN GRAN JARDINERO	2005	Outubro	Experiência	DSG
321	LA FIDELIDAD DE DISCIPULO	2005	Outubro	Experiência	BDC
322	LA EXPERIÉNCIA Y EL TIEMPO	2005	Novembro	Experiência	DSG
322	NUESTRAS SEDES ACROPOLITANAS	2005	Novembro	Experiência	BDC
323	EXPERIENCIA Y RENOVACIÓN	2005	Dezembro	Experiência	DSG
323	QUE SE ESPERA DE NOSOTROS? LA VICTORIA!	2005	Dezembro	Experiência	BDC
324	MENSAJE AÑO NUEVO 2006	2006	Janeiro	Dever	DSG
324	EL AÑO DEL DEBER	2006	Janeiro	Dever	DSG
325	DIFERENTES INTERPRETACIONES DEL DEBER	2006	Fevereiro	Dever	DSG
325	MANTENGAMOS LA UNIÓN EN EL TRABAJO	2006	Fevereiro	Dever	BDC
326	???	0	N/A	N/A	N/A
327	LA INTUICIÓN NACIDA DE DEBER	2006	Maio	Dever	DSG
327	LA DEVOCION	2006	Maio	Dever	BDC
328	EL DEBER Y LA RECTA ACCION	2006	Junho	Dever	DSG
328	A LOS NUEVOS ACROPOLITANOS	2006	Junho	Dever	BDC
329	EL DEBER Y EL TIEMPO	2006	Julho	Dever	DSG
329	FELIZ ANIVERSÁRIO HERMANOS ACROPOLITANOS!	2006	Julho	Dever	BDC
330	EL DEBER SER	2006	Agosto	Dever	DSG
330	QUÉ SIGNIFICA INTEGRASE AL IDEAL?	2006	Agosto	Dever	BDC
331	ALGUNOS CONSEJOS PARA SER COMO DEBEMOS SER	2006	Setembro	Dever	DSG
331	CÓMO MANTENER LA CONSCIENCIA DESPIERTA?	2006	Setembro	Dever	BDC
332	JUNTO A JAL	2006	Outubro	Dever	DSG
332	LA FORTUNA DE TENER MAESTROS	2006	Outubro	Dever	BDC
333	EL DEBER ANTE LAS CIRCUNSTANCIAS	2006	Novembro	Dever	DSG
333	EL BUEN HUMOR	2006	Novembro	Dever	BDC
334	EL DEBER HEROICO	2006	Dezembro	Dever	DSG
334	SIN PURIFICACIÓN NO HAU RENOVACIÓN	2006	Dezembro	Dever	BDC
335	MENSAJE AÑO NUEVO 2007	2007	Janeiro	Trilha	DSG
335	MENSAJE MM BDC - AÑO DEL SENDERO	2007	Janeiro	Trilha	BDC
336	EL SENDERO INTERIOR	2007	Fevereiro	Trilha	DSG
336	NUESTROS DESAFÍOS	2007	Fevereiro	Trilha	BDC
337	EL SENDERO: REALIZACIÓN Y EVOLUCIÓN	2007	Março	Trilha	DSG
337	EL ESPÍRITU HEROICO	2007	Março	Trilha	BDC
338	PERCORRER O CAMINHO COM RITMO	2007	Maio	Trilha	DSG
338	UNAMOS GERAÇÕES	2007	Maio	Trilha	BDC
339	EL SENDERO ASCENDENTE	2007	Junho	Trilha	DSG
339	NUESTRA VOCACIÓN HISTÓRICA	2007	Junho	Trilha	BDC
340	FELIZ ANIVERÁRIO, ACROPOLITANOS DO MUNDO! FELIZES 50 ANOS TRIUNFAIS!	2007	Julho	Trilha	BDC
340	CINQUENTA ANOS NO CAMINHO	2007	Julho	Trilha	DSG
341	AS PROVAS NO CAMINHO	2007	Agosto	Trilha	DSG
341	SEM ATENÇÃO NÃO HÁ EVOLUÇÃO	2007	Agosto	Trilha	BDC
342	OBSTÁCULOS NO CAMINHO	2007	Setembro	Trilha	DSG
342	IMPORTÂNCIA DA REFLEXÃO	2007	Setembro	Trilha	BDC
343	JAL, NOSSA PERMANENTE INSPIRAÇÃO	2007	Outubro	Trilha	BDC
343	O MESTRE E UM CAMINHO	2007	Outubro	Trilha	DSG
344	A TRILHA E AS CIRCUNSTÂNCIAS TEMPORÁRIAS	2007	Novembro	Trilha	DSG
344	ÂNIMO! A DISCIPLINA É POSSÍVEL	2007	Novembro	Trilha	BDC
345	A TRILHA E O SAGRADO	2007	Dezembro	Trilha	DSG
345	A FORTALEZA	2007	Dezembro	Trilha	BDC
346	MENSAGEM ANO NOVO 2008	2008	Janeiro	Duradouro	DSG
346	MENSAGEM DE ANO NOVO MM BDC - ANO DO DURADOURO	2008	Janeiro	Duradouro	BDC
347	O ESPÍRITO É DURADOURO	2008	Fevereiro	Duradouro	DSG
347	NOSSO IDEAL DE DAMAS E DE CAVALHEIROS	2008	Fevereiro	Duradouro	BDC
348	O DURADOURO. O QUE TROCA E O QUE PERMANECE	2008	Março	Duradouro	DSG
348	SUA ALMA É IMPORTANTE	2008	Março	Duradouro	BDC
349	NO MÊS DE MAIO, RECORDAMOS A HPB	2008	Maio	Duradouro	BDC
349	OS DESEJOS E A VONTADE	2008	Maio	Duradouro	DSG
350	A ESTABILIDADE	2008	Junho	Duradouro	DSG
350	O IDEALISTA E O DISCÍPULO	2008	Junho	Duradouro	BDC
351	A FELICIDADE	2008	Julho	Duradouro	DSG
351	NOVA ACRÓPOLE E UM IDEAL DE JUVENTUDE	2008	Julho	Duradouro	BDC
352	VALORES DURADOUROS	2008	Agosto	Duradouro	DSG
352	O ACROPOLITANO E O MAHABHARATA	2008	Agosto	Duradouro	BDC
353	OS SÍMBOLOS DO DURADOURO	2008	Setembro	Duradouro	DSG
353	OS KURAVAS DA ANSIEDADE	2008	Setembro	Duradouro	BDC
354	FOLHAS DE ÁLBUM	2008	Outubro	Duradouro	DSG
354	O PERIGOSO KURAVA DA MECANICIDADE	2008	Outubro	Duradouro	BDC
355	O DURADOURO E A RENOVAÇÃO	2008	Novembro	Duradouro	DSG
355	OS ACROPOLITANOS E A CRISE ECONÔMICA	2008	Novembro	Duradouro	BDC
356	O PACTO DE MILHOES DE ANOS	2008	Dezembro	Duradouro	DSG
356	O KURAVA DA CÓLERA OU DA IRA	2008	Dezembro	Duradouro	BDC
357	MENSAGE MMC DSG 2009	2009	Janeiro	Estabilidade	DSG
357	MENSAGEM DE ANO NOVO 2009	2009	Janeiro	Estabilidade	BDC
358	A COLUNA DA ESTABILIDADE	2009	Fevereiro	Estabilidade	DSG
358	O ORGULHO	2009	Fevereiro	Estabilidade	BDC
359	A ESTABILIDADE NA CRISE	2009	Março	Estabilidade	DSG
359	A DESCONFIANÇA	2009	Março	Estabilidade	BDC
360	A ESTABILIDADE NOS QUATRO ASPECTOS DA PERSONALIDADE	2009	Maio	Estabilidade	DSG
360	MANTENHA A UNIÃO	2009	Maio	Estabilidade	BDC
361	FATORES DE INSTABILIDADE	2009	Junho	Estabilidade	DSG
361	IMPORTÂNCIA DA BOA COMUNICAÇÃO PARA OBTER A CONVIVÊNCIA	2009	Junho	Estabilidade	BDC
362	A ESTABILIDADE E A VIDA	2009	Julho	Estabilidade	DSG
362	NOSSO IMPÉRIO	2009	Julho	Estabilidade	BDC
362	52º ANIVERSÁRIO DA OINA	2009	Julho	Estabilidade	DSG
363	PODER, ESTABILIDADE E VIDA	2009	Agosto	Estabilidade	DSG
363	O KURAVA DA VAIDADE	2009	Agosto	Estabilidade	BDC
364	OS QUATRO FATORES DE ESTABILIDADE	2009	Setembro	Estabilidade	DSG
364	OBEDIÊNCIA E DESOBEDIÊNCIA	2009	Setembro	Estabilidade	BDC
365	MESTRE JAL, NÓS, TEUS DISCÍPULOS, SEGUIMOS TEUS RASTROS	2009	Outubro	Estabilidade	BDC
365	DESCOBRINDO O IMPERECÍVEL	2009	Outubro	Estabilidade	DSG
366	A ORIENTAÇNAO DA COLUNA	2009	Novembro	Estabilidade	DSG
366	O CONFORMISMO	2009	Novembro	Estabilidade	BDC
367	COSTRUIR LA COLUMNA DE LA ESTABILIDAD	2009	Dezembro	Estabilidade	DSG
367	LA ENVIDIA	2009	Dezembro	Estabilidade	BDC
368	MENSAGEM DE ANO NOVO 2010 (DSG)	2010	Janeiro	Mérito	DSG
368	MENSAGEM DE ANO NOVO 2010 (MM BDC)	2010	Janeiro	Mérito	BDC
369	O QUE É O MÉRITO	2010	Fevereiro	Mérito	DSG
370	O MÉRITO COMO AÇÃO	2010	Março	Mérito	DSG
370	A RETIDÃO	2010	Março	Mérito	DSG
371	MÉRITOS PESSOAIS	2010	Maio	Mérito	DSG
371	A VIRTUDE DA PREVENÇÃO	2010	Maio	Mérito	DSG
372	CONQUISTAR MÉRITOS NOVOS	2010	Junho	Mérito	DSG
372	NECESSIDADE DE DESENVOLVER UMA RETA PRESENÇA DE ÂNIMO ANTE AS PROVAS	2010	Junho	Mérito	BDC
373	O MÉRITO E O KARMA	2010	Julho	Mérito	DSG
373	SABER PENSAR	2010	Julho	Mérito	BDC
374	O MÉRITO E DEMÉRITO	2010	Agosto	Mérito	DSG
374	SABER ESCOLHER	2010	Agosto	Mérito	BDC
375	???	2010	Setembro	Mérito	DSG
375	???	2010	Setembro	Mérito	BDC
376	SEM MÁSCARA	2010	Outubro	Mérito	DSG
376	INTERNET	2010	Outubro	Mérito	BDC
377	MÉRITOS PRÓPRIOS E ALHEIOS	2010	Novembro	Mérito	DSG
377	IMPORTÂNCIA DE UMA BOA INTEGRAÇÃO	2010	Novembro	Mérito	BDC
378	OS MÉRITOS SÃO DURADOUROS	2010	Dezembro	Mérito	DSG
378	DEVEMOS LIVERAR A ALMA DO PESO DAS EMOÇÕES NEGATIVAS	2010	Dezembro	Mérito	BDC
379	MENSAGEM DSG - ANO NOVO DE 2011	2011	Janeiro	Redenção	DSG
379	PALAVRAS MOTIVADAS PELO NOVO ANO DE 2011	2011	Janeiro	Redenção	BDC
380	A REDENÇÃO	2011	Fevereiro	Redenção	DSG
380	NOSSOS MEDOS	2011	Fevereiro	Redenção	BDC
381	PURIFICAÇÃO	2011	Março	Redenção	DSG
381	RECOMENDO-LHES TRIUNFAR	2011	Março	Redenção	BDC
382	A PRÓPRIA REDENÇÃO	2011	Maio	Redenção	DSG
382	AS FESTAS SAZONAIS	2011	Maio	Redenção	GAP
383	A ARTE DE SABER EXPRESSAR QUEIXAS, OU SOBRE A CRÍTICA CONSTRUTIVA	2011	Junho	Redenção	GAP
383	REDENÇÃO E CARMA	2011	Junho	Redenção	DSG
384	O QUE PODEMOS REDIMIR	2011	Julho	Redenção	DSG
384	OS ALIADOS ESCUROS	2011	Julho	Redenção	GAP
385	CULPABILIDADE E REDENÇÃO	2011	Agosto	Redenção	DSG
385	AS VIRTUDES COMO REALIDADES ENERGÉTICAS	2011	Agosto	Redenção	GAP
386	CONVICÇÃO	2011	Setembro	Redenção	DSG
386	NÃO SOMOS TOLOS	2011	Setembro	Redenção	GAP
387	EXISTEM OS MESTRES?	2011	Outubro	Redenção	DSG
387	A VELHA E A NOVA ACRÓPOLE	2011	Outubro	Redenção	GAP
388	DISCERNIMENTO	2011	Novembro	Redenção	DSG
388	ESTANDARTES	2011	Novembro	Redenção	GAP
388	AS VIRTUDES DE NOSSO TEMPLO INTERIOR	2011	Novembro	Redenção	GAP
389	AS MOTIVAÇÕES	2011	Dezembro	Redenção	DSG
389	A FELICIDADE: UM NOVO ÍNDICE DE DESENVOLVIMENTO	2011	Dezembro	Redenção	GAP
390	MENSAGEM DE DSG PARA O ANO NOVO	2012	Janeiro	Movimento	DSG
391	O MOVIMENTO	2012	Fevereiro	Movimento	DSG
391	A VIRTUDE DO RITMO	2012	Fevereiro	Movimento	GAP
392	UM IDEAL EM MOVIMENTO	2012	Março	Movimento	DSG
392	O CARÁTER COMO VIRTUDE	2012	Março	Movimento	GAP
393	ESPIRAIS E REDEMOINHOS	2012	Maio	Movimento	DSG
393	LIGAÇÕES COM NOSSO VELHO PASSADO	2012	Maio	Movimento	GAP
394	O MOVIMENTO E OS ARTEFATOS	2012	Julho	Movimento	DSG
394	COLOCAR UMA PEQUENA MAGIA NAS SECRETARIAS	2012	Junho	Movimento	GAP
395	MOVIMENTO E PURIFICAÇÃO	2012	Julho	Movimento	DSG
395	SOBRE NOSSA FILOSOFIA ACROPOLITANA	2012	Julho	Movimento	GAP
396	A INVESTIGAÇÃO	2012	Agosto	Movimento	DSG
396	NECESSITAMOS DE MAIS COESÃO	2012	Agosto	Movimento	GAP
397	O CAOS	2012	Setembro	Movimento	DSG
397	NECESSITAMOS TAMBÉM DE MAIOR COERÊNCIA	2012	Setembro	Movimento	GAP
398	AS DUAS FACES DO ESPELHO	2012	Outubro	Movimento	DSG
398	AS "TORRES DE TEMPO"	2012	Outubro	Movimento	GAP
399	OS TRÊS GRANDES FATORES DO MOVIMENTO: CALOR, ATRAÇÃO E REPULSÃO	2012	Novembro	Movimento	DSG
399	A ALQUIMIA DO DISCÍPULO	2012	Novembro	Movimento	GAP
400	A TRADIÇÃO	2012	Dezembro	Movimento	DSG
400	IMITAR O MESTRE OU SERMOS NÓS MESMOS?	2012	Dezembro	Movimento	GAP
401	MENSAGEM D.S.G. ANO NOVO	2013	Janeiro	Transmissão	DSG
401	SABER APRESENTAR A NOVA ACRÓPOLE	2013	Janeiro	Transmissão	GAP
402	A CORRENTE	2013	Fevereiro	Transmissão	DSG
402	A PIRÂMIDE DE NOSSO PROGRAMA DE ESTUDO	2013	Fevereiro	Transmissão	GAP
403	A TRANSMISSÃO E A AÇÃO	2013	Março	Transmissão	DSG
403	OBSTÁCULOS À IMAGINAÇÃO CRIADORA	2013	Março	Transmissão	GAP
404	A PRUDÊNCIA	2013	Maio	Transmissão	DSG
404	SER DISCÍPULOS OU SER "SEGUIDORES"	2013	Maio	Transmissão	GAP
405	BOA VONTADE	2013	Junho	Transmissão	DSG
405	A CLAREZA COMO VIRTUDE	2013	Junho	Transmissão	GAP
406	A TRANSMISSÃO E A UNIÃO	2013	Julho	Transmissão	DSG
406	ALGUNS CONSELHOS PRÁTICOS PARA SOLUCIONAR NOSSAS DIFICULDADES	2013	Julho	Transmissão	GAP
407	EL CORAZÓN	2013	Agosto	Transmissão	DSG
407	LA ESPERANZA	2013	Agosto	Transmissão	GAP
408	A PACIÊNCIA	2013	Setembro	Transmissão	DSG
408	CUIDADO COM AS REDES SOCIAIS EM INTERNET	2013	Setembro	Transmissão	GAP
409	A HARMONIA	2013	Outubro	Transmissão	DSG
409	A COMPENETRAÇÃO	2013	Outubro	Transmissão	GAP
409	ERA UMA VEZ...	2013	Outubro	Transmissão	DSG
410	NOVA ACRÓPOLE: FILOSOFIA, CULTURA E VOLUNTARIADO	2013	Novembro	Transmissão	GAP
410	A EVOLUÇÃO	2013	Novembro	Transmissão	DSG
411	TRANSMISSIÓN Y RECEPCIÓN	2013	Dezembro	Transmissão	DSG
411	LA TRANSMISSION Y SUS NIVELES	2013	Dezembro	Transmissão	GAP
412	MENSAGEM D.S.G. ANO NOVO	2014	Janeiro	Transformação	DSG
412	O FRACASSO DO MITO DO CRESCIMENTO ECONÔMICO INTERMINÁVEL	2014	Janeiro	Transformação	GAP
413	MUDANÇAS, TRANSFORMAÇÕES E TRANSMUTAÇÕES	2014	Fevereiro	Transformação	DSG
413	O PODER DO RISO	2014	Fevereiro	Transformação	GAP
414	TRANSFORMAÇÕES POSITIVAS E NEGATIVAS	2014	Março	Transformação	DSG
414	A PARÁBOLA DO BUDA E A ANCIÃ	2014	Março	Transformação	GAP
415	O LÓTUS BRANCO E O DISCÍPULO	2014	Maio	Transformação	DSG
415	AS MUDANÇA NO MUNDO E NOSSA ADAPTAÇÃO A ELAS	2014	Maio	Transformação	GAP
416	TRANSFORMAÇÕES: INOVAÇÃO, RENOVAÇÃO E RECUPERAÇÃO	2014	Junho	Transformação	DSG
416	O MUSEU DE JAL: NOSSO HEROON ATUAL	2014	Junho	Transformação	GAP
417	TRANSFORMAÇÕES HISTÓRICAS	2014	Julho	Transformação	DSG
417	ALGO PARA RECORDAR EM 15 DE JULHO	2014	Julho	Transformação	GAP
418	SÃO BOAS TODAS AS INOVAÇÕES?	2014	Agosto	Transformação	DSG
418	NOSSA ATITUDE NAS AULAS	2014	Agosto	Transformação	GAP
419	7 DE OUTUBRO: NO INVISÍVEL, JAL ESTÁ CONSCO...	2014	Setembro	Transformação	GAP
419	TRANSFORMAÇÕES: VELOCIDADE E SUPERFICIALIDADE	2014	Setembro	Transformação	DSG
420	7 DE SETEMBRO - 2014, ANO DAS TRANSFORMAÇÕES	2014	Outubro	Transformação	DSG/GAP
420	A PEDRA PRECIOSA DAS MIL FACES	2014	Outubro	Transformação	DSG
420	O DIA MUNDIAL DA FILOSOFIA	2014	Outubro	Transformação	GAP
421	A EVOLUÇÃO INTERIOR MUDA AS FORMAS	2014	Novembro	Transformação	DSG
421	TRANSFORMAÇÕES E TRANSMUTAÇÃO	2014	Novembro	Transformação	GAP
422	LA TRANSFORMACION DE LAS PRIORIDADES	2014	Dezembro	Transformação	DSG
422	EFECTOS DEL CAMBIO CLIMÁTICO	2014	Dezembro	Transformação	DSG
423	MENSAGEM D.S.G. ANO NOVO	2015	Janeiro	Renascimento	DSG
423	A IMPORTÂNCIA DOS PEQUENOS DETALHES	2015	Janeiro	Renascimento	GAP
424	O RENASCIMENTO INTERIOR	2015	Fevereiro	Renascimento	DSG
424	O QUE É SER IDEALISTA?	2015	Fevereiro	Renascimento	GAP
425	COMEÇAR A RENASCER	2015	Março	Renascimento	DSG
425	PARA O DIA DO LÓTUS BRANCO... TAMBÉM HÁ OUTRA PARÁBOLA	2015	Março	Renascimento	GAP
426	O RENASCIMENTO E O SER HUMANO	2015	Maio	Renascimento	DSG
426	OFERENDA	2015	Maio	Renascimento	DSG
427	RENOVAÇÃO E CONTINUIDADE	2015	Junho	Renascimento	DSG
427	UMA LIBERDADE FICTÍCIA	2015	Junho	Renascimento	DSG
428	É NECESSÁRIO PARA VÓS, RENASCER	2015	Julho	Renascimento	DSG
428	A IDADE MÉDIA JÁ ABRIU SUAS PORTAS...	2015	Julho	Renascimento	DSG
429	RENASCIMENTO E REGENERAÇÃO	2015	Agosto	Renascimento	DSG
429	O MISTÉRIO DA LINGUAGEM	2015	Agosto	Renascimento	DSG
430	RENASCIMENTO E VALOR	2015	Setembro	Renascimento	DSG
431	UN EJEMPLO ANUAL DE RENDIMIENTO	2015	Outubro	Renascimento	DSG
432	RENACIMIENTO Y PROGRESO	2015	Novembro	Renascimento	DSG
433	EL RENACER DE LA CONVIVENCIA	2015	Dezembro	Renascimento	DSG
434	MENSAGEM DO ANO DE 2016	2016	Janeiro	Harmonia	DSG
435	HARMONIA - UNIDADE - UNIÃO	2016	Fevereiro	Harmonia	DSG
436	HARMONIA E BELEZA	2016	Março	Harmonia	DSG
437	HARMONIA PROPORÇÃO - CARMA	2016	Maio	Harmonia	DSG
438	HARMONIA E UNIDADE	2016	Junho	Harmonia	DSG
439	A HARMONIA INTERIOR (O DOMÍNIO DE SI MESMO)	2016	Julho	Harmonia	DSG
440	HARMONIA E SAÚDE	2016	Agosto	Harmonia	DSG
441	A HARMONIA E A BONDADE	2016	Setembro	Harmonia	DSG
442	A HARMONIA DO MESTRE	2016	Outubro	Harmonia	DSG
443	O NASCIMENTO DA HARMONIA	2016	Novembro	Harmonia	DSG
444	A HARMONIA OCULTA	2016	Dezembro	Harmonia	DSG
445	MENSAGEM DE DSG DO ANO NOVO DE 2017	2017	Janeiro	Jubileu Renovado	DSG
446	DISTINTAS FORMAS DE MEMÓRIA	2017	Fevereiro	Jubileu Renovado	DSG
447	O SENTIDO DA BELEZA	2017	Março	Jubileu Renovado	DSG
448	PEDIR E DAR OPORTUNIDADES	2017	Abril	Jubileu Renovado	DSG
449	OS MESTRES	2017	Maio	Jubileu Renovado	DSG
450	O JUBILO, A ALEGRIA DE VIVER	2017	Junho	Jubileu Renovado	DSG
451	PRA QUE SERVE A FILOSOFIA	2017	Agosto	Jubileu Renovado	DSG
452	AS DUAS PONTES	2017	Setembro	Jubileu Renovado	DSG
453	A FELICIDADE DE CONVIVER COM UM SÁBIO	2017	Outubro	Jubileu Renovado	DSG
454	OS NOVOS IDIOMAS	2017	Novembro	Jubileu Renovado	DSG
455	O QUE NOS ENSINAM E O QUE APRENDEMOS	2017	Dezembro	Jubileu Renovado	DSG
456	ANO DA DIGNIDADE	2018	Janeiro	Dignidade	DSG
457	A DIGNIDADE E SEUS COLABORADORES	2018	Fevereiro	Dignidade	DSG
458	A DIGNIDADE E O PENSAMENTO	2018	Março	Dignidade	DSG
459	A DIGNDIADE E A SOBERANIA	2018	Maio	Dignidade	DSG
460	A DIGNIDADE DIANTE DA DOR E DA FELICIDADE	2018	Junho	Dignidade	DSG
461	A DIGNIDADE E A BENEVOLÊNCIA	2018	Julho	Dignidade	DSG
462	CRIAR A DIGNIDADE	2018	Agosto	Dignidade	DSG
463	DIGNIDADE: DE SABER LER A SABER FALAR	2018	Setembro	Dignidade	DSG
464	A DIGNIDADE, SEMPRE	2018	Outubro	Dignidade	DSG
465	A DIGNIDADE E A BELEZA	2018	Novembro	Dignidade	DSG
466	A DIGNIDADE E A ALMA	2018	Dezembro	Dignidade	DSG
467	MENSAGEM DO MM D S G DE ANO NOVO 2019	2019	Janeiro	Saúde	DSG
468	AS MÚLTIPLAS FACES DA SAÚDE	2019	Fevereiro	Saúde	DSG
469	TENSÃO E ATENÇÃO	2019	Março	Saúde	DSG
470	A SAÚDE DA ALMA	2019	Maio	Saúde	DSG
471	EVITAR O EXCESSO	2019	Junho	Saúde	DSG
472	A SAÚDE MENTAL: A SENSATEZ	2019	Julho	Saúde	DSG
473	POLUIÇÃO EXTERIOR E POLUIÇÃO INTERIOR	2019	Agosto	Saúde	DSG
474	O VERDADEIRO E O FALSO	2019	Setembro	Saúde	DSG
475	A OFERENDA PERMANTENTE	2019	Outubro	Saúde	DSG
476	SAÚDE E JUVENTUDE	2019	Novembro	Saúde	DSG
477	A SAÚDE E A META	2019	Dezembro	Saúde	DSG
478	MENSAGEM DE ANO NOVO	2020	Janeiro	Fortaleza	DSG
479	A GRATIDÃO	2020	Fevereiro	Fortaleza	DSG
480	A FORTALEZA ANTE AS DIFICULDADES	2020	Abril	Fortaleza	DSG
481	A VELHICE, A ENFERMIDADE E A MORTE	2020	Maio	Fortaleza	JCAP
481	O QUE É A FORTALEZA	2020	Maio	Fortaleza	DSG
482	O QUE É A FORTALEZA	2020	Junho	Fortaleza	DSG
483	53 ANOS DE UM IDEAL	2020	Julho	Fortaleza	DSG
483	ENCONTRAR O LUGAR EM ACRÓPOLE	2020	Julho	Fortaleza	JCAP
484	COMO CONSEGUIR A FORTALEZA	2020	Agosto	Fortaleza	DSG
485	COMPROVEM	2020	Setembro	Fortaleza	JCAP
485	GRATIDÃO E FORTALEZA	2020	Setembro	Fortaleza	DSG
486	O COFRE DO TESOURO	2020	Outubro	Fortaleza	DSG
487	INCERTEZA E FORTALEZA	2020	Novembro	Fortaleza	DSG
487	O QUE NÃO VEMOS	2020	Novembro	Fortaleza	JCAP
488	AS MIL FACES DA CAVERNA	2020	Dezembro	Fortaleza	DSG
489	MENSAGEM D.S.G. ANO NOVO 2021	2021	Janeiro	Identidade	DSG
490	A IDENTIDADE E AS PROVAS	2021	Fevereiro	Identidade	DSG
490	ESTAR NA DEFENSIVA	2021	Fevereiro	Identidade	JCAP
491	A IDENTIDADE NA PERSONALIDADE	2021	Março	Identidade	DSG
492	CONHECE-TE A TI MESMO	2021	Abril	Identidade	DSG
492	A ENERGIA DISCIPULAR	2021	Abril	Identidade	JCAP
493	MAIO: MÊS DE MESTRES E DISCÍPULOS	2021	Maio	Inidetidade	DSG
494	ENCONTRAR A IDENTIDADE	2021	Julho	Identidade	DSG
494	CAMINHAR PARA NOSSO DESTINO	2021	Julho	Identidade	JCAP
495	A CONCENTRAÇÃO PARA CHEGAR À IDENTIDADE	2021	Agosto	Identidade	DSG
496	O QUE SE PASSA COM A TERRA E SEUS HABITANTES?	2021	Setembro	Identidade	DSG
497	UM NOVO JUBILEU	2021	Outubro	Identidade	DSG
498	OS ANTIGOS ESTOICOS VEM HOJE EM NOSSA AJUDA	2021	Novembro	Identidade	DSG
498	A MAIORIA SILENCIOSA	2021	Novembro	Identidade	JCAP
499	A SERENIDADE	2021	Dezembro	Identidade	DSG
500	MENSAGEM D.S.G. ANO NOVO 2022	2022	Janeiro	Fidelidade	DSG
501	O PEQUENO E O GRANDE TEMPO	2022	Fevereiro	Fidelidade	DSG
501	O MOTOR INTERNO	2022	Fevereiro	Fidelidade	JCAP
502	O TEMPO HOMOGÊNEO	2022	Abril	Fidelidade	DSG
503	AO TEMPO MEMÓRIA DE TODOS OS MESTRES	2022	Maio	Fidelidade	DSG
503	CORRENTE DISCIPULAR E COMPROMISSO	2022	Maio	Fidelidade	JCAP
505	NOSSO ANIVERSÁRIO	2022	Julho	Fidelidade	DSG
505	ESTAMOS VIVOS!	2022	Julho	Fidelidade	JCAP
506	A FIDELIDADE, ESPELHO DA ALMA	2022	Agosto	Fidelidade	DSG
507	VIVER EM UM MUNDO ITINERANTE	2022	Setembro	Fidelidade	DSG
507	REFLEXÃO APÓS A VITÓRIA	2022	Setembro	Fidelidade	JCAP
508	FIDELIDADE AOS MESTRES	2022	Outubro	Fidelidade	DSG
509	FIDELIDADE E CONVICÇÃO	2022	Novembro	Fidelidade	DSG
509	FIDELIDADE À TERRA	2022	Novembro	Fidelidade	JCAP
510	FIDELIDADE AO TEMPO	2022	Dezembro	Fidelidade	DSG
511	MENSAGEM D.S.G. ANO NOVO	2023	Janeiro	Cordura (Lucidez)	DSG
512	A LUCIDEZ	2023	Fevereiro	Cordura (Lucidez)	DSG
512	OS NÍVEIS EM NOVA ACRÓPOLE	2023	Fevereiro	Cordura (Lucidez)	JCAP
513	A LUCIDEZ COMO JUSTO MEIO	2023	Abril	Cordura (Lucidez)	DSG
514		2023	Junho	Cordura (Lucidez)	DSG
515	PARA QUE SERVE A LUCIDEZ	2023	Julho	Cordura (Lucidez)	DSG
516		2023	Agosto	Cordura (Lucidez)	DSG
517		2023	Setembro	Cordura (Lucidez)	DSG
518		2023	Outubro	Cordura (Lucidez)	DSG
519		2023	Novembro	Cordura (Lucidez)	DSG
520		2023	Dezembro	Cordura (Lucidez)	DSG
521		2023	Dezembro	Cordura (Lucidez)	DSG
`;

export const BASTIOES_DB = rawBastiões.split('\n')
  .filter(line => line.trim().length > 0)
  .map(line => {
    const cols = line.split('\t');
    const idNum = cols[0] ? cols[0].trim() : '';
    const titulo = cols[1] ? cols[1].trim() : '';
    const ano = cols[2] ? cols[2].trim() : '';
    
    // Ignora linhas incompletas ou que não tenham ID válido
    if (!idNum || !titulo || isNaN(parseInt(idNum, 10))) return null;

    return {
      numero: idNum,
      titulo: titulo,
      ano: ano,
      nomeCompleto: `Bastião ${idNum} (${ano}) - ${titulo}`,
      link: gerarLinkDoKoha(ano)
    };
  })
  .filter(Boolean); // Limpa os nulls

export const virtues = [
    // --- VIRTUDES CLÁSSICAS ---
    { 
      name: "Paciência", 
      shortDesc: "Uma forma de fé", 
      description: "Capacidade de suportar as adversidades sem se alterar, compreendendo os ritmos naturais do tempo e o processo das coisas.", 
      practices: "• Não reagir à primeira provocação\n• Esperar 10 segundos antes de responder\n• Aceitar o ritmo das outras pessoas", 
      internalPractices: "• Suportar as dificuldades da filiação sem críticas\n• Aguardar o ritmo natural da Escola\n• Exercer paciência com as falhas dos irmãos de ideal",
      quote: "A paciência não é a capacidade de esperar, mas como nos comportamos enquanto esperamos.", quoteAuthor: "J.A. Livraga", color: "#4A90E2" 
    },
    { 
      name: "Coragem", 
      shortDesc: "Agir com o coração", 
      description: "Não é a ausência do medo, mas a ação decidida e reta, movida pelo dever, apesar da presença do medo.", 
      practices: "• Fazer o que deve ser feito, mesmo com receio\n• Assumir a responsabilidade de um erro\n• Defender a verdade de forma justa",
      internalPractices: "• Assumir missões e responsabilidades no GDVE\n• Enfrentar o 'Kurava' dominante apontado pela IA\n• Defender os ideais acropolitanos perante o mundo", 
      quote: "Coragem é a resistência ao medo, o domínio do medo, e não a ausência do medo.", quoteAuthor: "Mark Twain", color: "#E74C3C" 
    },
    { 
      name: "Prudência", 
      shortDesc: "Sabedoria prática em ação", 
      description: "O discernimento que permite escolher os melhores caminhos e meios para alcançar um fim nobre.", 
      practices: "• Avaliar consequências antes de agir\n• Buscar conselho de pessoas sábias\n• Silenciar quando não se tem certeza",
      internalPractices: "• Consultar o Instrutor/Mestre antes de grandes decisões\n• Aplicar o discernimento (Viveka) nas ações\n• Preservar o silêncio e o mistério das práticas", 
      quote: "A prudência é a verdadeira mãe de todas as virtudes.", quoteAuthor: "Cícero", color: "#16A085" 
    },
    { 
      name: "Justiça", 
      shortDesc: "Dar a cada um de acordo com sua natureza e seus atos", 
      description: "A busca pelo equilíbrio e equidade, não segundo a conveniência egoísta, mas segundo a Lei Universal.", 
      practices: "• Não julgar por simpatias ou antipatias\n• Cumprir com as próprias obrigações\n• Reconhecer o mérito do outro",
      internalPractices: "• Agir de acordo com o Dharma\n• Cumprir rigorosamente suas escalas de serviço\n• Ser impecavelmente justo no trato com os companheiros", 
      quote: "A justiça não é outra coisa senão a conveniência do homem em sociedade.", quoteAuthor: "Platão", color: "#C0392B" 
    },
    { 
      name: "Disciplina", 
      shortDesc: "O alinhamento interior", 
      description: "O método pelo qual o ser humano alinha sua personalidade inferior aos propósitos de sua consciência superior.", 
      practices: "• Cumprir o cronograma estabelecido para o dia\n• Não ceder à preguiça em tarefas diárias\n• Terminar rigorosamente o que se começou",
      internalPractices: "• Fazer o Tratak e práticas diárias sem negociar\n• Assiduidade impecável nas atividades da filial\n• Cumprir os preceitos do Código de Honra", 
      quote: "A disciplina é a ponte entre as metas e as realizações.", quoteAuthor: "Jim Rohn", color: "#34495E" 
    },
    { 
      name: "Devoção", 
      shortDesc: "O Amor à verdade", 
      description: "O amor profundo que move o ser humano a entregar-se a uma causa sagrada ou a um ideal nobre.", 
      practices: "• Realizar ações cotidianas com elevado propósito\n• Manter o ambiente de estudo limpo e organizado\n• Ler textos atemporais com respeito e foco",
      internalPractices: "• Cultivar Bhakti pelo Ideal e pelo Mestre\n• Realizar limpezas e serviços como oferenda\n• Reverenciar os Símbolos da Escola", 
      quote: "Aquele que realiza todas as suas ações por Mim, e para quem Eu sou a meta suprema, esse chega a Mim.", quoteAuthor: "Bhagavad Gita", color: "#9B59B6" 
    },
    
    // --- PILARES FUNDAMENTAIS ---
    { 
      name: "Investigação", 
      shortDesc: "A busca pela Verdade", 
      description: "O estudo que não aceita dogmas cegos, mas busca ativamente as leis universais na Natureza e no homem.", 
      practices: "• Questionar os porquês antes de aceitar\n• Ler e meditar sobre uma página de filosofia profunda\n• Observar atentamente as leis da natureza",
      internalPractices: "• Aprofundar-se nos ensinamentos do Módulo GDVE\n• Realizar o autoexame de Kurukshetra com rigor\n• Estudo comparado de Religiões, Ciências e Artes", 
      quote: "Não há religião superior à Verdade.", quoteAuthor: "H.P. Blavatsky", color: "#2980B9" 
    },
    { 
      name: "Serviço", 
      shortDesc: "A Prática da Verdade", 
      description: "O ato de colocar as próprias mãos e mente a serviço da humanidade, sem buscar recompensas.", 
      practices: "• Fazer um trabalho invisível que ninguém quer fazer\n• Ajudar proativamente uma causa ou comunidade\n• Renunciar ao conforto pessoal por um dever",
      internalPractices: "• Acumular horas reais de trabalho na Filial\n• Apoiar ativamente as demandas do GAF\n• Praticar o Karma Yoga: ação sem apego", 
      quote: "Dorme o homem que trabalha para si. Desperta o que trabalha para a humanidade.", quoteAuthor: "J.A. Livraga", color: "#F39C12" 
    },
    { 
      name: "Generosidade", 
      shortDesc: "Gerar para dar", 
      description: "Compartilhar tempo, atenção e recursos de forma ampla, expandindo os próprios limites da bondade.", 
      practices: "• Ouvir alguém ativamente sem interromper\n• Partilhar conhecimento sem vaidade intelectual\n• Doar tempo de qualidade para apoiar alguém",
      internalPractices: "• Dar oportunidades de serviço e brilho ao outro\n• Compartilhar sabedoria fraterna nas reuniões\n• Apoiar financeiramente ou materialmente a Escola", 
      quote: "O pouco que se dá com o coração vale muito; o muito que se dá sem ele, não vale nada.", quoteAuthor: "Délia Steinberg Guzmán", color: "#27AE60" 
    },
    { 
      name: "Beleza", 
      shortDesc: "O resplendor da Verdade", 
      description: "A percepção estética e moral da harmonia em todas as coisas e ações do cotidiano.", 
      practices: "• Ouvir música clássica ou elevada com atenção\n• Arrumar-se e vestir-se com dignidade\n• Falar palavras limpas, evitando a vulgaridade",
      internalPractices: "• Cuidar da estética e limpeza do Templo/Filial\n• Contemplar a Arte como via de ascensão\n• Harmonizar o próprio discurso nas reuniões GDVE", 
      quote: "A beleza é o esplendor da verdade.", quoteAuthor: "Platão", color: "#E84393" 
    },
    { 
      name: "Bondade", 
      shortDesc: "A manifestação do Bem", 
      description: "A inclinação natural da Vontade em direção ao bem, promovendo a compaixão e o amparo.", 
      practices: "• Evitar completamente a crítica destrutiva\n• Treinar o olhar para o lado luminoso das pessoas\n• Agir imediatamente para aliviar a carga do outro",
      internalPractices: "• Ter compaixão estoica pelas falhas dos confrades\n• Fazer críticas apenas se forem construtivas e ao Diretor\n• Zelar ativamente pela fraternidade da filial", 
      quote: "A verdadeira bondade consiste não apenas em não fazer o mal, mas em nem sequer desejá-lo.", quoteAuthor: "Sêneca", color: "#FF69B4" 
    },
    { 
      name: "Ordem", 
      shortDesc: "A expressão da harmonia", 
      description: "A capacidade de alinhar a própria vida, o espaço ao redor e os pensamentos a um ritmo estruturado.", 
      practices: "• Arrumar a própria cama logo pela manhã\n• Manter a mesa de trabalho e papéis organizados\n• Focar em fazer apenas uma coisa de cada vez",
      internalPractices: "• Preencher a Carta de Degrau sem atrasos\n• Cumprir Item 3 e 4 (Trabalho Ordenado e Eficaz)\n• Alinhar o próprio ritmo ao ritmo das Forças da Natureza", 
      quote: "A ordem é a primeira lei do céu.", quoteAuthor: "Alexander Pope", color: "#7B68EE" 
    },
    
    // --- O FOGO E A MENTE ---
    { 
      name: "Entusiasmo", 
      shortDesc: "En Theos, com o Sagrado dentro", 
      description: "A energia vibrante que contagia as pessoas, dando força para continuar a marcha perante os obstáculos.", 
      practices: "• Sorrir intencionalmente perante uma dificuldade\n• Transmitir ânimo a quem está reclamando\n• Realizar uma tarefa monótona com alegria",
      internalPractices: "• Cultivar o 'En Theos' (Deus dentro) diariamente\n• Ser um motor de ânimo dentro do grupo GAF\n• Acordar almas adormecidas pela ação e exemplo", 
      quote: "O entusiasmo é a força divina em movimento; é Deus no homem.", quoteAuthor: "Délia Steinberg Guzmán", color: "#FF5722" 
    },
    { 
      name: "Vontade", 
      shortDesc: "O motor do Espírito", 
      description: "Não o mero desejo, mas a força reta que corta a inércia e concretiza decisões na matéria.", 
      practices: "• Fazer imediatamente algo que se está adiando\n• Controlar um pequeno impulso do corpo\n• Impor a si mesmo uma renúncia temporária",
      internalPractices: "• Acionar o Ícto espiritual contra as desculpas\n• Ficar imóvel fisicamente nas práticas de câmara\n• Forjar o combate direto no diário do Kurukshetra", 
      quote: "Onde há Vontade, há um Caminho.", quoteAuthor: "Sri Ram", color: "#C0392B" 
    },
    { 
      name: "Atenção", 
      shortDesc: "O Foco da Consciência", 
      description: "A capacidade de estar plenamente focado. Aonde vai a atenção, vai a energia e a vida.", 
      practices: "• Escutar alguém sem formular respostas mentais\n• Fazer uma caminhada prestando atenção nos passos\n• Exercícios visuais de fixação e observação",
      internalPractices: "• Praticar o Tratak Diário sem pestanejar\n• Otimizar Economia de Tempo e Energia (Item 5)\n• Manter o Prana ancorado no presente durante rituais", 
      quote: "Atenção é o caminho para a imortalidade; a desatenção é o caminho da morte.", quoteAuthor: "Dhammapada", color: "#3498DB" 
    },
    { 
      name: "Memória", 
      shortDesc: "Fidelidade a nós mesmos (nossa Alma)", 
      description: "O resgate consciente das lições já aprendidas e da própria identidade e propósito de vida.", 
      practices: "• Revisar mentalmente os eventos do dia anterior\n• Lembrar diariamente do porquê iniciou um projeto\n• Fazer um diário retrospectivo com fidelidade",
      internalPractices: "• Executar o Exercício Pitagórico noturno\n• Recordar a Tradição e os Bastiões lidos\n• Preencher o Prólogo e Epílogo para fixar a mente", 
      quote: "O homem é sua memória. A memória é a força da nossa identidade.", quoteAuthor: "J.A. Livraga", color: "#8E44AD" 
    },
    
    // --- O GUERREIRO INTERIOR ---
    { 
      name: "Perseverança", 
      shortDesc: "Repetir com Consciência, buscando Aperfeiçoamento", 
      description: "A força para levantar-se após um erro, retomar o passo e continuar marchando sem ceder à frustração.", 
      practices: "• Voltar a um hábito saudável que foi abandonado\n• Tentar resolver um problema mais uma vez\n• Eliminar completamente a auto-justificativa",
      internalPractices: "• Preencher a cota de Item 7 (Virtudes) da Carta\n• Levantar-se rapidamente de falhas relatadas no GDVE\n• Não abandonar a Filial perante as crises de personalidade", 
      quote: "A perseverança é mãe da boa sorte.", quoteAuthor: "Miguel de Cervantes", color: "#D35400" 
    },
    { 
      name: "Constância", 
      shortDesc: "Esperar enquanto Trabalha, sem cair no Desânimo", 
      description: "O nível maduro da perseverança: manter um ritmo inalterado, que não depende de humores ou motivação passageira.", 
      practices: "• Executar o planejamento do dia sem vontade\n• Manter a rotina de preenchimento do Diário\n• Cumprir horários com precisão absoluta",
      internalPractices: "• Vencer as 'Leis da Matéria' e ciclicidades (Item 2)\n• Sustentar o 'Streak' ininterrupto de Práticas FV\n• Frequência impecável nas reuniões do Grupo", 
      quote: "A gota d'água perfura a rocha não pela sua força, mas pela sua constância.", quoteAuthor: "Ovídio", color: "#2ECC71" 
    },
    { 
      name: "Intuição", 
      shortDesc: "Compreensão além da Mente", 
      description: "A percepção direta de algo profundo, que ultrapassa a lógica mecânica e o raciocínio comum.", 
      practices: "• Observar simbolismos nos acontecimentos do dia\n• Confiar na voz da consciência para escolhas morais\n• Desconectar das telas para ouvir o próprio silêncio",
      internalPractices: "• Buscar o clarão de Buddhi além de Kama-Manas\n• Extrair o sentido real por trás dos mitos estudados\n• Escutar o Mestre Interior na Câmara de Purificação", 
      quote: "A intuição não é a inimiga da razão, mas sua sucessora alada.", quoteAuthor: "J.A. Livraga", color: "#9B59B6" 
    },
    { 
      name: "Ousadia", 
      shortDesc: "Atrever-se a ser melhor", 
      description: "A atitude de lançar-se rumo a um ideal, rompendo fronteiras de conformismo e timidez.", 
      practices: "• Dar o primeiro passo prático em um projeto engavetado\n• Falar a verdade quando todos estão calados\n• Mudar intencionalmente uma rotina que traz muito conforto",
      internalPractices: "• Assumir frentes de trabalho ou docência na Escola\n• Apresentar palestras e superar o medo do público\n• Assumir as Missões de Ciclo (IA) sem hesitar", 
      quote: "Ousai, e vossas forças aumentarão.", quoteAuthor: "Joana d'Arc", color: "#E67E22" 
    },
    
    // --- O CAMINHO ALQUÍMICO ---
    { 
      name: "Transmutar", 
      shortDesc: "O chumbo em ouro - Mudar de dentro para fora", 
      description: "A arte interior de pegar emoções densas (raiva, medo, angústia) e elevá-las a qualidades superiores.", 
      practices: "• Converter uma ofensa em uma resposta de amabilidade\n• Usar o cansaço como combustível para o dever\n• Calar-se quando a vontade mecânica é reclamar",
      internalPractices: "• Varrer por Dentro (Item 1) para dissolver os nós psíquicos\n• Combater os Vícios e a negligência de frente (Item 6)\n• Aplicar a Alquimia ensinada no Módulo Avançado", 
      quote: "O Universo é transformação; a nossa vida é o que os nossos pensamentos fazem dela.", quoteAuthor: "Marco Aurélio", color: "#F1C40F" 
    },
    { 
      name: "Concórdia", 
      shortDesc: "O corações unificados", 
      description: "A capacidade humana de unir diferentes pessoas em torno de um Ideal único, ignorando vaidades.", 
      practices: "• Ceder numa discussão onde o orgulho quer vencer\n• Evitar debates sobre futilidades divisivas\n• Unir pessoas que possuem habilidades complementares",
      internalPractices: "• Manter o Corpo GDVE unido sob tensão\n• Trabalhar com confrades de temperamentos difíceis\n• Elevar a egrégora da filial de Barra do Garças", 
      quote: "Se quereis que vosso coração encontre concórdia, ide ao centro, que é o Espírito.", quoteAuthor: "Sri Ram", color: "#1ABC9C" 
    },
    { 
      name: "Fortaleza", 
      shortDesc: "O pilar na tormenta", 
      description: "A firmeza de caráter para não desmoronar perante o peso das crises externas e internas.", 
      practices: "• Manter-se produtivo em dias de caos\n• Ser o apoio de amigos que estão desesperados\n• Enfrentar mudanças bruscas sem lamentação",
      internalPractices: "• Agir como autêntico Bastião na defesa da Instituição\n• Blindar-se contra o falatório externo e as Leis da Matéria\n• Suportar o rito de passagem do Discipulado", 
      quote: "Sofre e suporta: não há homem forte sem o fogo da provação.", quoteAuthor: "Sêneca", color: "#7F8C8D" 
    },
    { 
      name: "Nobreza", 
      shortDesc: "Elevação de caráter", 
      description: "Viver e agir acima da mediocridade do mundo. Um estado de espírito que se recusa a ser vulgar.", 
      practices: "• Portar-se com etiqueta e asseio mesmo quando sozinho\n• Recusar fazer comentários rasteiros ou fofocas\n• Tratar pessoas simples com extrema reverência",
      internalPractices: "• Viver como as autênticas Damas e Cavalheiros\n• Jamais profanar os símbolos e ambientes da Ordem\n• Resgatar a moral clássica em pleno Século XXI", 
      quote: "A verdadeira nobreza está em sermos superiores ao nosso antigo eu.", quoteAuthor: "Ernest Hemingway", color: "#FFD700" 
    },
    { 
      name: "Integração", 
      shortDesc: "Tornar completo", 
      description: "Compreender que não somos seres isolados, mas partes ativas de um Grande Corpo ou sistema.", 
      practices: "• Pensar no bem de um grupo antes da conveniência pessoal\n• Somar esforços sem exigir os holofotes\n• Ver-se como um elo entre o passado e o futuro familiar",
      internalPractices: "• Sincronizar as ações diárias com as metas da Filial\n• Operar como uma única mente no corpo do GDVE\n• Reconhecer-se como instrumento da Cadeia Hierárquica", 
      quote: "O que não é útil ao enxame, não é útil à abelha.", quoteAuthor: "Marco Aurélio", color: "#3498DB" 
    },
    
    // --- O COMPROMISSO ---
    { 
      name: "Dever", 
      shortDesc: "Compromisso com a Finalidade", 
      description: "Fazer o que é certo puramente porque é o certo, dispensando cálculos de fuga ou recompensa.", 
      practices: "• Executar tarefas pendentes sem hesitar\n• Não abandonar obrigações por capricho emocional\n• Fazer mais do que o estritamente cobrado",
      internalPractices: "• O Dever como manifestação do Dharma\n• Cumprir as missões de IA sem negociação com o ego\n• Apresentar a Carta de Degrau impreterivelmente na data", 
      quote: "Faça o seu dever, porque a ação é melhor do que a inação.", quoteAuthor: "Bhagavad Gita", color: "#C0392B" 
    },
    { 
      name: "Dignidade", 
      shortDesc: "O valor imutável do Ser", 
      description: "Manter-se erguido internamente. Ter profundo respeito por si mesmo e pela condição humana.", 
      practices: "• Cumprir todas as promessas que fez no dia\n• Não rir do que denigre outras pessoas\n• Manter o controle emocional em discussões",
      internalPractices: "• Viver e respirar o Código de Honra diariamente\n• Proteger a Egrégora da Escola com a própria postura\n• Manter a coluna ereta, o símbolo da verticalidade interna", 
      quote: "Nenhum homem é livre se não for senhor de si mesmo.", quoteAuthor: "Epicteto", color: "#8E44AD" 
    },
    { 
      name: "Fidelidade", 
      shortDesc: "Lealdade ao que há de mais Elevado", 
      description: "A firmeza de sustentar juramentos, ideias e vínculos mesmo nos momentos de distanciamento ou escuridão.", 
      practices: "• Fazer a coisa certa quando ninguém está fiscalizando\n• Honrar compromissos feitos há muito tempo\n• Proteger segredos e confidências depositadas em você",
      internalPractices: "• Cumprir os ritos e a Forja mesmo estando sozinho em casa\n• Honrar os compromissos assumidos perante o Mestre\n• Preservar e proteger os materiais internos da Ordem", 
      quote: "O verdadeiro cavaleiro é aquele que se mantém fiel quando todos os outros fogem.", quoteAuthor: "J.A. Livraga", color: "#2980B9" 
    },
    { 
      name: "Mística", 
      shortDesc: "Boa Vontade e Eficácia", 
      description: "O estado de espírito que permite enxergar a assinatura do Eterno por trás das formas da Natureza.", 
      practices: "• Entrar em contato com o ar livre e a natureza com reverência\n• Refletir filosoficamente sobre a transitoriedade da vida\n• Purificar o ambiente antes de ler ou trabalhar",
      internalPractices: "• Construção ativa das 4 fases do Templo Interior\n• Transformar as Aulas em Ritos de Conhecimento\n• Perceber o mistério nas diretrizes da Escola", 
      quote: "Mística é ter sede de Deus.", quoteAuthor: "J.A. Livraga", color: "#6C3483" 
    },
    { 
      name: "Discipulado", 
      shortDesc: "Viver o que se Aprende", 
      description: "A postura de quem reconhece que nada sabe e se coloca disposto a aprender com a Vida e com os sábios.", 
      practices: "• Receber correções e feedback sem justificativas na ponta da língua\n• Procurar o ensinamento oculto atrás de uma frustração\n• Imitar o exemplo ético das grandes figuras da história",
      internalPractices: "• Ouvir o Instrutor da filial sem o ruído do intelecto\n• Transmitir fidedignamente o que recebeu, sem alterar a fonte\n• Compreender a obediência como liberdade estruturada", 
      quote: "Quando o discípulo está pronto, o Mestre aparece.", quoteAuthor: "O Caibalion", color: "#27AE60" 
    }
  ];

export const philosophicalQuotes = [
    // Clássicos e Estoicos
    { text: "Que ninguém hesite em se dedicar à filosofia enquanto jovem, nem se canse de fazê-lo depois de velho.", author: "Epicuro" },
    { text: "Não é porque as coisas são difíceis que não ousamos; é porque não ousamos que elas são difíceis.", author: "Sêneca" },
    { text: "A felicidade não consiste em adquirir e gozar, mas em não desejar nada.", author: "Epicteto" },
    { text: "Conhece-te a ti mesmo e conhecerás o universo e os deuses.", author: "Oráculo de Delfos" },
    { text: "A vida não examinada não vale a pena ser vivida.", author: "Sócrates" },
    { text: "Não percas tempo discutindo sobre o que um homem bom deve ser. Sê um.", author: "Marco Aurélio" },
    { text: "Tudo o que ouvimos é uma opinião, não um fato. Tudo o que vemos é uma perspectiva, não a verdade.", author: "Marco Aurélio" },
    { text: "O homem corajoso não é o que não sente medo, mas o que conquista esse medo.", author: "Aristóteles" },
    
    // Sabedoria Oriental e Esotérica
    { text: "O homem é feito pela sua crença. Como ele acredita, assim ele é.", author: "Bhagavad Gita" },
    { text: "A mente é tudo. O que você pensa, você se torna.", author: "Buda" },
    { text: "O maior domínio é o domínio de si mesmo.", author: "Buda" },
    { text: "Não há religião superior à verdade.", author: "H. P. Blavatsky" },
    { text: "Seja indulgente com as fraquezas alheias, mas rigoroso com as suas próprias.", author: "H. P. Blavatsky (A Voz do Silêncio)" },
    { text: "O sábio molda a si mesmo.", author: "Dhammapada" },
    { text: "Para o homem resoluto e determinado, não existe a palavra impossível.", author: "Sri Ram" },

    // Nova Acrópole (Jorge Ángel Livraga e Délia Steinberg)
    { text: "A melhor maneira de vencer as trevas não é lutar contra elas, mas acender uma luz.", author: "J.A. Livraga" },
    { text: "Um Ideal é o oxigênio da Alma.", author: "J.A. Livraga" },
    { text: "Temos que forjar uma Juventude que não precise de esperanças artificiais, mas da força dos seus próprios Ideais.", author: "J.A. Livraga" },
    { text: "As circunstâncias não fazem o homem, apenas o revelam a si mesmo.", author: "Epicteto / J.A. Livraga" },
    { text: "Ser filósofo não é ler muitos livros, é saber extrair sabedoria de cada ato da Vida.", author: "Délia Steinberg Guzmán" },
    { text: "O heroísmo cotidiano consiste em fazer o bem, de forma oculta e perseverante, todos os dias.", author: "Délia Steinberg Guzmán" },
    { text: "É inútil buscar a paz no mundo se não soubermos plantá-la no coração.", author: "Délia Steinberg Guzmán" },
    { text: "Vontade não é desejar as coisas, é sacrificar-se por elas.", author: "J.A. Livraga" },
    
    // Sabedoria Universal Complementar
    { text: "Mesmo a jornada de mil milhas começa com um único passo.", author: "Lao Tsé" },
    { text: "Aquele que conhece os outros é sábio; aquele que conhece a si mesmo é iluminado.", author: "Lao Tsé" },
    { text: "A verdadeira medida de um homem não se vê nos momentos de conforto, mas nos de desafio e controvérsia.", author: "Martin Luther King Jr." }
  ];

export const studyTips = [
    { phase: "E - Examinar", text: "Antes de iniciar a leitura, reserve 5 minutos para examinar o índice, os títulos e os resumos. Crie um mapa mental do que o autor pretende explorar." },
    { phase: "E - Examinar", text: "Leia o prefácio e a conclusão antes do primeiro capítulo. Entender o destino final facilita a jornada pela obra." },
    { phase: "P - Perguntar", text: "Transforme o título do capítulo em uma pergunta. O que você espera que o texto responda? Leia ativamente buscando essa resposta." },
    { phase: "P - Perguntar", text: "Um livro de sabedoria não é um monólogo. Faça perguntas ao texto enquanto lê: 'Como posso aplicar isso na minha vida amanhã?'" },
    { phase: "L - Ler", text: "Leia com um lápis em mãos. Sublinhe não apenas frases bonitas, mas os eixos centrais do pensamento lógico do autor." },
    { phase: "L - Ler", text: "Se a leitura estiver muito densa, diminua o ritmo. Livros clássicos devem ser mastigados, não engolidos." },
    { phase: "R - Rememorar", text: "Ao terminar um capítulo, feche o livro e tente explicar o que leu em voz alta, como se ensinasse a um amigo. Teste sua síntese." },
    { phase: "R - Rememorar", text: "Se você não consegue resumir a ideia principal da página que acabou de ler, volte. A retenção real exige atenção e repetição." },
    { phase: "R - Rever", text: "Reserve um dia da semana apenas para rever suas anotações e fichamentos. O ouro da leitura filosófica está na revisão." },
    { phase: "R - Rever", text: "Conecte o novo aprendizado com o que você já sabe. A sabedoria é uma teia viva, não uma gaveta de informações isoladas." },
    { phase: "Prática Geral", text: "Não meça seu avanço pela quantidade de páginas viradas, mas pela quantidade de ideias que você transformou em ação." },
    { phase: "Prática Geral", text: "É preferível ler poucos livros bons muitas vezes, do que muitos livros ruins uma só vez." }
  ];

 // A Grade Curricular de Leitura Obrigatória
export const GRADE_CURRICULAR = [
  // --- PRIMEIRO ANO ---
  { id: 'g1', title: 'A República', author: 'Platão', stage: '1º Ano' },
  { id: 'g2', title: 'Bhagavad Gita', author: 'Vyasa', stage: '1º Ano' },
  { id: 'g3', title: 'A Voz do Silêncio', author: 'H.P. Blavatsky', stage: '1º Ano' },
  { id: 'g4', title: 'O Ideal Político', author: 'Jorge Ángel Livraga', stage: '1º Ano' },
  { id: 'g5', title: 'Fundamentos do Ideal Acropolitano', author: 'Jorge Ángel Livraga', stage: '1º Ano' },
  
  // --- SEGUNDO ANO ---
  { id: 'g6', title: 'Dhammapada', author: 'Siddhartha Gautama (Buda)', stage: '2º Ano' },
  { id: 'g7', title: 'Analectos', author: 'Confúcio', stage: '2º Ano' },
  { id: 'g8', title: 'Meditações', author: 'Marco Aurélio', stage: '2º Ano' },
  { id: 'g9', title: 'Manual', author: 'Epicteto', stage: '2º Ano' },
  { id: 'g10', title: 'Sobre a Brevidade da Vida', author: 'Sêneca', stage: '2º Ano' },
  
  // --- TERCEIRO ANO ---
  { id: 'g11', title: 'Ética a Nicômaco', author: 'Aristóteles', stage: '3º Ano' },
  { id: 'g12', title: 'História', author: 'Heródoto', stage: '3º Ano' }
];